// Paper strip and reference list strings (paperStrip.ts, paperRefs.ts).
import { messages } from '../../shared/i18n';

export const S = messages({
  ko: {
    // Kind badge tooltips
    kindSurvey: '서베이/리뷰 논문 (제목·유형으로 판별)',
    kindConference: '학회(컨퍼런스) 논문',
    kindJournal: '저널 논문',
    kindTechnical: '기술 보고서 / 학위논문',
    kindPreprint: '프리프린트 (출판본 미확인)',
    // Reference list fallback reasons (the sentence's lead clause + the shared ending)
    refsBudgetSpent: (s2Limited: boolean) => 'OpenAlex는 일일 무료 한도가 소진돼 조회하지 못했고' + (s2Limited ? ' Semantic Scholar는 요청 제한(429)에 걸렸으며' : ''),
    refsS2Limited: 'OpenAlex에 참고문헌 목록이 없고 Semantic Scholar는 요청 제한(429)으로 확인하지 못했으며',
    refsNoList: 'OpenAlex·Semantic Scholar에 참고문헌 목록이 없고',
    refsPaperNotFound: '이 논문을 OpenAlex·Semantic Scholar에서 못 찾았고',
    refsNotInPdfEither: (lead: string) => `${lead}, PDF에서도 참고문헌 절을 찾지 못했습니다.`,
    // Status line
    notRecognized: '논문으로 인식되지 않았습니다.',
    notRecognizedNoIds: '첫 페이지와 문서 정보에서 DOI·arXiv ID·제목을 찾지 못했습니다.',
    whatDoi: (doi: string) => `DOI ${doi}`,
    whatArxiv: (id: string) => `arXiv:${id}`,
    whatTitle: (title: string) => `제목 "${title}"`,
    lookingUp: (what: string) => `${what} 조회 중…`,
    lookupFailedNetwork: (what: string) => `${what}: OpenAlex·Crossref·Semantic Scholar 조회가 실패했습니다 (네트워크 지연 또는 요청 제한).`,
    lookupFailedS2Limited: (what: string) => `${what}: OpenAlex·Crossref에 없고, Semantic Scholar는 요청 제한(429)으로 확인하지 못했습니다. 설정에 Semantic Scholar API 키를 넣으면 안정적으로 조회됩니다.`,
    lookupFailedNotFound: (what: string) => `${what}: 어느 데이터베이스(OpenAlex·Crossref·Semantic Scholar)에도 없습니다.`,
    lookupFailedLimited: (what: string, sources: string) => `${what}: ${sources}의 요청 제한(429)으로 확인하지 못했습니다. 잠시 뒤 다시 파싱해 보세요.`,
    matchedByTitle: '제목으로 찾음',
    matchedByTitleDetail: '이 PDF에 DOI·arXiv ID가 없어 제목과 첫 저자 이름으로 찾은 논문입니다. 드물게 다른 논문일 수 있습니다.',
    notRecognizedSearched: (what: string) => `${what}(으)로 OpenAlex·Crossref·Semantic Scholar를 찾아봤지만 일치하는 논문이 없습니다.`,
    processingError: (message: string) => `논문 정보를 처리하는 중 오류: ${message}`,
    // Strip
    paperInfo: '논문정보',
    noInfo: (reason: string) => `정보 없음: ${reason}`,
    noVenue: '게재처(저널/학회)를 못 찾았습니다.',
    noYear: '출판 연도를 못 찾았습니다.',
    twoYearPartial: (percent: number) => `OpenAlex가 이 논문의 인용을 일부만 알고 있어(전체의 ${percent}%) 최근 2년 인용을 계산하지 않았습니다.`,
    twoYearNoHistory: '연도별 인용 데이터가 없어 최근 2년 인용을 계산하지 못했습니다 (OpenAlex).',
    citesLabel: '2년/전체 인용수',
    noCitationCount: '인용 수를 Semantic Scholar·OpenAlex·Crossref 어디서도 못 찾았습니다.',
    s2RateLimited: 'Semantic Scholar 조회가 요청 제한(429)으로 실패해 실제보다 낮을 수 있습니다. 설정에 Semantic Scholar API 키를 넣으면 안정적으로 조회됩니다.',
    citesTooltip: (sources: string) => `올해·작년 인용 (OpenAlex 연도별) / 전체 인용 = 소스 최대값 (${sources}).\nGoogle Scholar는 프리프린트·학위논문·중복 레코드까지 합산해 보통 더 높습니다.`,
    citationChartLabel: '연도별 인용 그래프',
    referencesLabel: '참고문헌',
    noReferenceCount: '참고문헌 수를 Crossref·OpenAlex·Semantic Scholar 어디서도 못 찾았습니다.',
    referencesCountedFromPdf: 'PDF 본문의 참고문헌 목록에서 센 수 (데이터베이스의 수보다 많음)',
    copyBibtex: 'BibTeX 복사',
    copyApa: 'APA 7 서식 복사',
    authorsMore: (n: number) => ` 외 ${n}명`,
    venueMeanCitedness: (value: string) => `게재처 2년 평균 피인용 ${value} (IF와 같은 정의, OpenAlex)`,
    noVenueMeanCitedness: '⚠︎ 게재처 2년 평균 피인용을 OpenAlex에서 못 찾았습니다.',
    copied: '복사됨',
    copyFailed: '실패',
    // Reference list
    untitled: '(제목 없음)',
    pdfListBasis: 'PDF 본문의 목록 기준',
    s2Basis: 'Semantic Scholar 기준 · 게재처 IF 지표는 OpenAlex 전용',
    refsNotFound: '참고문헌 목록을 못 찾았습니다.',
    refsPreparing: '참고문헌 목록 준비 중…',
    refsSearching: '참고문헌 목록 찾는 중…',
    refsLoadingLabel: (n: number, expected: number) => `불러오는 중 ${n}/${expected}`,
    refsDoneLabel: (n: number) => `${n}편 · 인용 많은 순`,
    refsHeader: (label: string) => `참고문헌 ${label}`,
    refsMissingInOpenAlex: (n: number) => ` · ${n}편은 OpenAlex에 없음`,
    authorsEtAl: (list: string) => `${list} 외`,
    citedCount: (count: string) => `인용 ${count}`,
    notFoundInOpenAlex: 'OpenAlex에서 못 찾음',
    noCitationCountShort: '⚠︎ 인용 수 없음',
    venueMeanCitednessShort: '게재처 2년 평균 피인용 (OpenAlex)',
    pdfNote: (linked: number, total: number) => `PDF 본문의 목록 기준 · OpenAlex 연결 ${linked}/${total}`,
    budgetSpentNote: ' (OpenAlex 일일 한도 소진 — 설정에 API 키를 넣으면 연결됩니다)',
    titlesLeftNote: (n: number) => ` · 제목 연결 남음 ${n}편 (목록을 열 때마다 조금씩)`,
  },
  en: {
    kindSurvey: 'Survey / review paper (judged from title and type)',
    kindConference: 'Conference paper',
    kindJournal: 'Journal paper',
    kindTechnical: 'Technical report / thesis',
    kindPreprint: 'Preprint (no published version found)',
    refsBudgetSpent: (s2Limited: boolean) => 'OpenAlex’s daily free limit is used up' + (s2Limited ? ' and Semantic Scholar is rate-limited (429)' : ''),
    refsS2Limited: 'OpenAlex has no reference list and Semantic Scholar is rate-limited (429)',
    refsNoList: 'OpenAlex and Semantic Scholar have no reference list',
    refsPaperNotFound: 'This paper wasn’t found in OpenAlex or Semantic Scholar',
    refsNotInPdfEither: (lead: string) => `${lead}, and no references section was found in the PDF either.`,
    notRecognized: 'Not recognized as a paper.',
    notRecognizedNoIds: 'No DOI, arXiv ID or title found on the first page or in the document info.',
    whatDoi: (doi: string) => `DOI ${doi}`,
    whatArxiv: (id: string) => `arXiv:${id}`,
    whatTitle: (title: string) => `title "${title}"`,
    lookingUp: (what: string) => `Looking up ${what}…`,
    lookupFailedNetwork: (what: string) => `${what}: lookup in OpenAlex, Crossref and Semantic Scholar failed (network delay or rate limit).`,
    lookupFailedS2Limited: (what: string) => `${what}: not in OpenAlex or Crossref, and Semantic Scholar is rate-limited (429). Adding a Semantic Scholar API key in settings makes lookups reliable.`,
    lookupFailedNotFound: (what: string) => `${what}: not in any database (OpenAlex, Crossref, Semantic Scholar).`,
    lookupFailedLimited: (what: string, sources: string) => `${what}: ${sources} rate-limited the lookup (429). Try reparsing in a moment.`,
    matchedByTitle: 'matched by title',
    matchedByTitleDetail: 'This PDF names no DOI or arXiv ID, so the paper was found by its title and first author. Rarely, it may be a different paper.',
    notRecognizedSearched: (what: string) => `Searched OpenAlex, Crossref and Semantic Scholar for ${what}, but found no matching paper.`,
    processingError: (message: string) => `Error while processing paper info: ${message}`,
    paperInfo: 'Paper info',
    noInfo: (reason: string) => `No info: ${reason}`,
    noVenue: 'Couldn’t find the venue (journal/conference).',
    noYear: 'Couldn’t find the publication year.',
    twoYearPartial: (percent: number) => `OpenAlex knows only part of this paper’s citations (${percent}% of the total), so last-2-years citations weren’t calculated.`,
    twoYearNoHistory: 'No per-year citation data, so last-2-years citations couldn’t be calculated (OpenAlex).',
    citesLabel: '2-yr / total citations',
    noCitationCount: 'Couldn’t find a citation count in Semantic Scholar, OpenAlex or Crossref.',
    s2RateLimited: 'The Semantic Scholar lookup failed because of rate limiting (429), so this may be lower than the real count. Adding a Semantic Scholar API key in settings makes lookups reliable.',
    citesTooltip: (sources: string) => `This year’s + last year’s citations (OpenAlex, per year) / total citations = highest across sources (${sources}).\nGoogle Scholar usually shows more because it also counts preprints, theses and duplicate records.`,
    citationChartLabel: 'Citations per year chart',
    referencesLabel: 'References',
    noReferenceCount: 'Couldn’t find a reference count in Crossref, OpenAlex or Semantic Scholar.',
    referencesCountedFromPdf: 'Counted from the reference list in the PDF (higher than the databases’ count)',
    copyBibtex: 'Copy BibTeX',
    copyApa: 'Copy in APA 7 format',
    authorsMore: (n: number) => `, +${n} more`,
    venueMeanCitedness: (value: string) => `Venue 2-year mean citedness ${value} (same definition as IF, OpenAlex)`,
    noVenueMeanCitedness: '⚠︎ Couldn’t find the venue’s 2-year mean citedness in OpenAlex.',
    copied: 'Copied',
    copyFailed: 'Failed',
    untitled: '(untitled)',
    pdfListBasis: 'based on the list in the PDF',
    s2Basis: 'based on Semantic Scholar · venue IF is OpenAlex only',
    refsNotFound: 'Couldn’t find the reference list.',
    refsPreparing: 'Preparing the reference list…',
    refsSearching: 'Looking for the reference list…',
    refsLoadingLabel: (n: number, expected: number) => `loading ${n}/${expected}`,
    refsDoneLabel: (n: number) => `${n} · most cited first`,
    refsHeader: (label: string) => `References: ${label}`,
    refsMissingInOpenAlex: (n: number) => ` · ${n} not in OpenAlex`,
    authorsEtAl: (list: string) => `${list} et al.`,
    citedCount: (count: string) => `Cited ${count}`,
    notFoundInOpenAlex: 'Not found in OpenAlex',
    noCitationCountShort: '⚠︎ No citation count',
    venueMeanCitednessShort: 'Venue 2-year mean citedness (OpenAlex)',
    pdfNote: (linked: number, total: number) => `based on the list in the PDF · ${linked}/${total} matched in OpenAlex`,
    budgetSpentNote: ' (OpenAlex’s daily limit is used up — add an API key in settings to connect)',
    titlesLeftNote: (n: number) => ` · ${n} left to match by title (a few each time the list opens)`,
  },
});
