// Strings of the PDF viewer's parts (pdfViewer/*.ts: figure capture, sidebar,
// properties dialog, annotation conflict, print, citation chart, ...).
import { messages } from '../../shared/i18n';

export const S = messages({
  ko: {
    // Figure capture
    captureHintDrag: '복사할 영역을 드래그하세요 · Esc 끄기',
    captureHintFinding: '그림·표 찾는 중… · 그동안 영역을 드래그해도 됩니다 · Esc 끄기',
    captureHintFound: (n: number) => `그림·표 ${n}개 · 눌러서 복사하거나 영역을 드래그하세요 · Esc 끄기`,
    captureHintNone: '찾은 그림·표 없음 · 복사할 영역을 드래그하세요 · Esc 끄기',
    captureDialog: '그림 복사',
    captureSource: '출처',
    captureOptions: '옵션',
    captureWhite: '흰색',
    captureTransparent: '투명',
    captureCopyWhen: '캡처하면',
    captureCopyNone: '복사 안 함',
    captureCopyImageOnly: '이미지 복사 (슬라이드)',
    captureCopyImageSource: '이미지와 출처 복사 (문서)',
    captureCopySourceOnly: '출처만 복사',
    captureEmbed: '이미지 아래에 출처 넣기',
    captureShort: '짧게',
    captureApa: 'APA 전체',
    captureNone: '없음',
    captureClick: '누르면 복사 · 드래그하면 영역 지정',
    captureFigureN: (n: string | number) => `그림 ${n}`,
    captureTableN: (n: string | number) => `표 ${n}`,
    captureFigure: '그림',
    captureCopyAria: (what: string) => `${what} 복사`,
    captureClose: '닫기 (Esc)',
    captureCloseAria: '닫기',
    captureCopyImage: '이미지 복사',
    captureCopySource: '출처 복사',
    captureSavePng: 'PNG 저장',
    captureAnnotations: '주석·필기 포함',
    captureDpi: '해상도',
    captureBackground: '배경',
    captureStyle: '형식',
    capturePrefix: '머리말',
    captureNoPdf: '열린 PDF가 없습니다.',
    capturePngFailed: 'PNG 변환에 실패했습니다.',
    captureCopying: '복사하는 중…',
    captureCopiedSeparate: (what: string) => `${what} 이미지 복사됨 · 출처는 [출처 복사]`,
    captureCopiedTogether: (what: string) => `${what} 이미지와 출처 복사됨`,
    captureCopyFailed: (message: string) => `복사하지 못했습니다: ${message}`,
    captureSourceCopied: '출처 복사됨',
    captureNotCopied: '복사하지 않았습니다 · 아래 버튼으로 복사하세요',
    captureResult: '캡처 결과',
    captureToastImage: (what: string) => `${what} 이미지 복사됨`,
    captureToastSource: (what: string) => `${what} 출처 복사됨`,
    captureToastNone: (what: string) => `${what} 캡처됨`,
    captureSourceCopyFailed: (message: string) => `출처를 복사하지 못했습니다: ${message}`,
    captureSaving: '저장하는 중…',
    captureSaved: 'PNG 저장됨',
    captureSaveFailed: (message: string) => `저장하지 못했습니다: ${message}`,
    captureAsLatex: 'LaTeX로',
    // LaTeX (formula) capture
    latexHintFinding: '수식 찾는 중… · 그동안 수식 영역을 드래그해도 됩니다 · Esc 끄기',
    latexHintFound: (n: number) => `수식 ${n}개 · 눌러서 LaTeX로 복사하거나 영역을 드래그하세요 · Esc 끄기`,
    latexHintNone: '찾은 수식 없음 · 수식 영역을 드래그하세요 · Esc 끄기',
    latexFormula: '수식',
    latexClick: '누르면 LaTeX로 복사 · 드래그하면 영역 지정',
    latexCopyAria: '수식을 LaTeX로 복사',
    latexResult: 'LaTeX 결과',
    latexText: '읽은 LaTeX (고칠 수 있음)',
    latexLoading: '수식 인식 모델 불러오는 중… (처음 한 번)',
    latexReading: '수식을 LaTeX로 읽는 중…',
    latexCopied: 'LaTeX 복사됨',
    latexCopiedUnsure: 'LaTeX 복사됨 · 확신이 낮으니 확인하세요',
    latexCopiedAs: (what: string) => `${what} 복사됨`,
    latexNotFormula: '수식으로 읽지 못했습니다 · 본문이 섞이지 않게 수식만 감싸 보세요',
    latexFailed: (message: string) => `읽지 못했습니다: ${message}`,
    latexCopy: 'LaTeX 복사',
    latexCopyTitle: '고친 내용 그대로 복사',
    latexInlineTitle: '$…$ (본문 속 수식)로 감싸 복사',
    latexDisplayTitle: '$$…$$ (별도 줄 수식)로 감싸 복사',
    // Annotations
    swatch: (color: string) => `색상 ${color}`,
    conflictSummary: (fileOnly: number, cacheOnly: number) =>
      `이 PDF 파일에는 브라우저에 없는 필기 ${fileOnly}개가, `
      + `브라우저에는 파일에 없는 필기 ${cacheOnly}개가 저장돼 있습니다. 어느 쪽을 유지할까요?`,
    // Sidebar
    pageN: (n: number) => `페이지 ${n}`,
    noOutline: '목차가 없습니다.',
    toggleChildren: '하위 항목 접기/펼치기',
    untitled: '(제목 없음)',
    noAttachments: '첨부파일이 없습니다.',
    // Print
    printPreparing: (n: number, total: number) => `인쇄 준비 중… ${n} / ${total}`,
    // Citation chart
    chartAria: '연도별 인용 수',
    chartEmpty: '연도별 인용 데이터가 없습니다.',
    chartYear: (year: number | string) => `${year}년`,
    chartCitations: (count: string) => ` 인용 ${count}회`,
    chartCumulative: (count: string) => ` · 누적 ${count}회`,
    // Document properties
    propFileName: '파일 이름',
    propFileSize: '파일 크기',
    propTitle: '제목',
    propAuthor: '작성자',
    propSubject: '주제',
    propKeywords: '키워드',
    propCreated: '만든 날짜',
    propModified: '수정한 날짜',
    propCreator: '제작 프로그램',
    propProducer: 'PDF 생성 프로그램',
    propVersion: 'PDF 버전',
    propPageCount: '페이지 수',
    propPageSize: '페이지 크기',
    propFastWebView: '빠른 웹 보기',
    yes: '예',
    no: '아니요',
    landscape: '가로',
    portrait: '세로',
    // OpenAlex
    openAlexBudget: 'OpenAlex의 무료 일일 한도(같은 네트워크가 함께 씀)를 다 써서 OpenAlex를 조회하지 못했습니다. 설정에 OpenAlex API 키(무료)를 넣으면 계속 조회됩니다.',
  },
  en: {
    captureHintDrag: 'Drag an area to copy · Esc to exit',
    captureHintFinding: 'Finding figures and tables… · you can drag an area meanwhile · Esc to exit',
    captureHintFound: (n: number) => `${n} found · click one to copy it, or drag an area · Esc to exit`,
    captureHintNone: 'No figures or tables found · drag an area to copy · Esc to exit',
    captureDialog: 'Copy figure',
    captureSource: 'Source',
    captureOptions: 'Options',
    captureWhite: 'White',
    captureTransparent: 'Transparent',
    captureCopyWhen: 'On capture',
    captureCopyNone: 'Copy nothing',
    captureCopyImageOnly: 'Copy the image (slides)',
    captureCopyImageSource: 'Copy image and source (documents)',
    captureCopySourceOnly: 'Copy the source only',
    captureEmbed: 'Source below the image',
    captureShort: 'Short',
    captureApa: 'Full APA',
    captureNone: 'None',
    captureClick: 'Click to copy · drag to select an area',
    captureFigureN: (n: string | number) => `Figure ${n}`,
    captureTableN: (n: string | number) => `Table ${n}`,
    captureFigure: 'Figure',
    captureCopyAria: (what: string) => `Copy ${what}`,
    captureClose: 'Close (Esc)',
    captureCloseAria: 'Close',
    captureCopyImage: 'Copy image',
    captureCopySource: 'Copy source',
    captureSavePng: 'Save PNG',
    captureAnnotations: 'Include annotations',
    captureDpi: 'Resolution',
    captureBackground: 'Background',
    captureStyle: 'Format',
    capturePrefix: 'Prefix',
    captureNoPdf: 'No PDF is open.',
    capturePngFailed: 'Couldn’t convert to PNG.',
    captureCopying: 'Copying…',
    captureCopiedSeparate: (what: string) => `${what} image copied · use “Copy source” for the citation`,
    captureCopiedTogether: (what: string) => `${what} image and source copied`,
    captureCopyFailed: (message: string) => `Couldn’t copy: ${message}`,
    captureSourceCopied: 'Source copied',
    captureNotCopied: 'Nothing copied · use the buttons below',
    captureResult: 'Capture',
    captureToastImage: (what: string) => `${what} image copied`,
    captureToastSource: (what: string) => `${what} source copied`,
    captureToastNone: (what: string) => `${what} captured`,
    captureSourceCopyFailed: (message: string) => `Couldn’t copy the source: ${message}`,
    captureSaving: 'Saving…',
    captureSaved: 'PNG saved',
    captureSaveFailed: (message: string) => `Couldn’t save: ${message}`,
    captureAsLatex: 'As LaTeX',
    // LaTeX (formula) capture
    latexHintFinding: 'Finding formulas… · you can drag around a formula meanwhile · Esc to turn off',
    latexHintFound: (n: number) => `${n} formula${n === 1 ? '' : 's'} · click one to copy it as LaTeX, or drag an area · Esc to turn off`,
    latexHintNone: 'No formulas found · drag around a formula · Esc to turn off',
    latexFormula: 'Formula',
    latexClick: 'Click to copy as LaTeX · drag to select an area',
    latexCopyAria: 'Copy formula as LaTeX',
    latexResult: 'LaTeX result',
    latexText: 'LaTeX read (editable)',
    latexLoading: 'Loading the formula model… (first time only)',
    latexReading: 'Reading the formula as LaTeX…',
    latexCopied: 'LaTeX copied',
    latexCopiedUnsure: 'LaTeX copied · not sure of it, please check',
    latexCopiedAs: (what: string) => `${what} copied`,
    latexNotFormula: 'Couldn’t read a formula · select just the formula, without body text',
    latexFailed: (message: string) => `Couldn’t read it: ${message}`,
    latexCopy: 'Copy LaTeX',
    latexCopyTitle: 'Copy as edited',
    latexInlineTitle: 'Copy wrapped in $…$ (inline math)',
    latexDisplayTitle: 'Copy wrapped in $$…$$ (display math)',
    swatch: (color: string) => `Color ${color}`,
    conflictSummary: (fileOnly: number, cacheOnly: number) =>
      `This PDF file has ${fileOnly} ${fileOnly === 1 ? 'annotation that isn’t' : 'annotations that aren’t'} in the browser, `
      + `and the browser has ${cacheOnly} ${cacheOnly === 1 ? 'annotation that isn’t' : 'annotations that aren’t'} in the file. Which would you like to keep?`,
    pageN: (n: number) => `Page ${n}`,
    noOutline: 'No outline.',
    toggleChildren: 'Expand or collapse child items',
    untitled: '(Untitled)',
    noAttachments: 'No attachments.',
    printPreparing: (n: number, total: number) => `Preparing to print… ${n} / ${total}`,
    chartAria: 'Citations per year',
    chartEmpty: 'No citation data by year.',
    chartYear: (year: number | string) => `${year}`,
    chartCitations: (count: string) => ` ${count} ${count === '1' ? 'citation' : 'citations'}`,
    chartCumulative: (count: string) => ` · ${count} total`,
    propFileName: 'File name',
    propFileSize: 'File size',
    propTitle: 'Title',
    propAuthor: 'Author',
    propSubject: 'Subject',
    propKeywords: 'Keywords',
    propCreated: 'Created',
    propModified: 'Modified',
    propCreator: 'Application',
    propProducer: 'PDF producer',
    propVersion: 'PDF version',
    propPageCount: 'Number of pages',
    propPageSize: 'Page size',
    propFastWebView: 'Fast web view',
    yes: 'Yes',
    no: 'No',
    landscape: 'landscape',
    portrait: 'portrait',
    openAlexBudget: 'OpenAlex’s free daily limit (shared by everyone on the same network) has been used up, so OpenAlex couldn’t be queried. Add a free OpenAlex API key in settings to keep looking things up.',
  },
});
