// Messages the service worker sends back to pages (errors and sync statuses).
import { messages } from '../shared/i18n';

export const S = messages({
  ko: {
    // Request validation
    badRequest: '요청 형식이 올바르지 않습니다.',
    badSyncStatusRequest: '동기화 상태 요청 형식이 올바르지 않습니다.',
    badSyncRequest: '동기화 요청 형식이 올바르지 않습니다.',
    badConnectRequest: 'Google 연결 요청 형식이 올바르지 않습니다.',
    badDisconnectRequest: 'Google 연결 해제 요청 형식이 올바르지 않습니다.',
    badSyncSettingRequest: '동기화 설정 요청 형식이 올바르지 않습니다.',
    badSyncHint: '동기화 힌트 형식이 올바르지 않습니다.',
    badLibraryRequest: '라이브러리 요청 형식이 올바르지 않습니다.',
    badOpenDefaultViewerRequest: '기본 PDF 뷰어 열기 요청 형식이 올바르지 않습니다.',
    badPdfTabRequest: 'PDF 탭 요청 형식이 올바르지 않습니다.',
    badPdfTabState: 'PDF 탭 상태 형식이 올바르지 않습니다.',
    badProjectRequest: '프로젝트 요청 형식이 올바르지 않습니다.',
    badOpenProjectRequest: '프로젝트 열기 요청 형식이 올바르지 않습니다.',
    badMoveProjectRequest: '프로젝트 이동 요청 형식이 올바르지 않습니다.',
    badRestoreTabsRequest: '뷰어 탭 복구 요청 형식이 올바르지 않습니다.',
    badSyncWebRoutingRequest: '웹 PDF 라우팅 동기화 요청 형식이 올바르지 않습니다.',
    tabNotFound: '탭 정보를 찾을 수 없습니다.',
    noSuchProject: '없는 프로젝트입니다.',
    projectLimit: (max: number) => `프로젝트는 ${max}개까지 만들 수 있습니다. 쓰지 않는 프로젝트를 삭제한 뒤 다시 시도하세요.`,
    folderLimit: (max: number) => `폴더는 ${max}개까지 만들 수 있습니다. 쓰지 않는 폴더를 삭제한 뒤 다시 시도하세요.`,
    fileAccessOff: '파일 URL 액세스가 꺼져 있어 로컬 파일로 이동할 수 없습니다.',
  },
  en: {
    badRequest: 'Invalid request.',
    badSyncStatusRequest: 'Invalid sync status request.',
    badSyncRequest: 'Invalid sync request.',
    badConnectRequest: 'Invalid Google connect request.',
    badDisconnectRequest: 'Invalid Google disconnect request.',
    badSyncSettingRequest: 'Invalid sync settings request.',
    badSyncHint: 'Invalid sync hint.',
    badLibraryRequest: 'Invalid library request.',
    badOpenDefaultViewerRequest: 'Invalid request to open in the default PDF viewer.',
    badPdfTabRequest: 'Invalid PDF tab request.',
    badPdfTabState: 'Invalid PDF tab state.',
    badProjectRequest: 'Invalid project request.',
    badOpenProjectRequest: 'Invalid request to open a project.',
    badMoveProjectRequest: 'Invalid request to move to a project.',
    badRestoreTabsRequest: 'Invalid request to restore viewer tabs.',
    badSyncWebRoutingRequest: 'Invalid request to sync web PDF routing.',
    tabNotFound: 'Couldn’t find the tab.',
    noSuchProject: 'That project doesn’t exist.',
    projectLimit: (max: number) => `You can have up to ${max} projects. Delete one you no longer use and try again.`,
    folderLimit: (max: number) => `You can have up to ${max} folders. Delete one you no longer use and try again.`,
    fileAccessOff: 'File URL access is turned off, so it can’t switch to the local file.',
  },
});
