// Messages the service worker sends back to pages (errors and sync statuses).
import { messages } from '../shared/i18n';

export const S = messages({
  ko: {
    // Request validation
    badRequest: '요청 형식이 올바르지 않습니다.',
    badSyncStatusRequest: '동기화 상태 요청 형식이 올바르지 않습니다.',
    badSyncRequest: '동기화 요청 형식이 올바르지 않습니다.',
    badConnectRequest: 'Google 연결 요청 형식이 올바르지 않습니다.',
    badDisconnectRequest: 'Google 연결 해제 요청 형식이 올바르지 않습니다.',
    badSyncSettingRequest: '동기화 설정 요청 형식이 올바르지 않습니다.',
    badSyncHint: '동기화 힌트 형식이 올바르지 않습니다.',
    badLibraryRequest: '라이브러리 요청 형식이 올바르지 않습니다.',
    badOpenDefaultViewerRequest: '기본 PDF 뷰어 열기 요청 형식이 올바르지 않습니다.',
    badPdfTabRequest: 'PDF 탭 요청 형식이 올바르지 않습니다.',
    badPdfTabState: 'PDF 탭 상태 형식이 올바르지 않습니다.',
    badProjectRequest: '프로젝트 요청 형식이 올바르지 않습니다.',
    badOpenProjectRequest: '프로젝트 열기 요청 형식이 올바르지 않습니다.',
    badMoveProjectRequest: '프로젝트 이동 요청 형식이 올바르지 않습니다.',
    badRestoreTabsRequest: '뷰어 탭 복구 요청 형식이 올바르지 않습니다.',
    badSyncWebRoutingRequest: '웹 PDF 라우팅 동기화 요청 형식이 올바르지 않습니다.',
    tabNotFound: '탭 정보를 찾을 수 없습니다.',
    noSuchProject: '없는 프로젝트입니다.',
    fileAccessOff: '파일 URL 액세스가 꺼져 있어 로컬 파일로 이동할 수 없습니다.',
    // Google sign-in
    authBadResponse: 'Google 로그인 응답이 올바르지 않습니다.',
    authVerifyFailed: 'Google 로그인 응답을 검증하지 못했습니다.',
    authExpired: 'Google 로그인이 만료되었습니다. 설정에서 Google 계정을 다시 연결하세요.',
    authDenied: 'Google 계정 접근이 허용되지 않았습니다.',
    authFailed: 'Google 로그인에 실패했습니다.',
    authDriveDenied: 'Google Drive 앱 데이터 접근 권한이 허용되지 않았습니다.',
    authServerUnreachable: 'Google 인증 서버에 연결하지 못했습니다.',
    tokenVerifyFailed: 'Google 토큰을 검증하지 못했습니다.',
    syncNotConfigured: '이 빌드에는 Google 동기화가 구성되어 있지 않습니다.',
    authCancelled: 'Google 로그인이 취소되었습니다.',
    accountMismatch: '연결된 Google 계정과 다른 계정으로 로그인되어 있습니다. 설정에서 다시 연결하세요.',
    // Google Drive
    driveFileTooLarge: 'Google Drive의 동기화 파일이 너무 큽니다.',
    driveReadFailed: 'Google Drive의 동기화 파일을 읽지 못했습니다.',
    driveQuotaExceeded: 'Google Drive 저장 공간이 부족합니다.',
    driveRateLimited: 'Google Drive 요청 한도를 초과했습니다. 잠시 후 다시 시도하세요.',
    driveDenied: 'Google Drive 접근이 거부되었습니다.',
    driveHttpError: (status: number) => `Google Drive 요청이 실패했습니다 (HTTP ${status}).`,
    driveBadUrl: 'Google Drive 요청 주소가 올바르지 않습니다.',
    syncTimeout: '동기화 요청 시간이 초과되었습니다.',
    driveUnreachable: 'Google Drive에 연결하지 못했습니다.',
    driveBadResponse: 'Google Drive 응답을 해석하지 못했습니다.',
    driveUploadSessionFailed: 'Google Drive 업로드 세션을 열지 못했습니다.',
    driveUploadUnverified: 'Google Drive 업로드 결과를 확인하지 못했습니다.',
    accountInfoFailed: 'Google 계정 정보를 확인하지 못했습니다.',
    driveFileChanging: 'Google Drive 파일이 계속 변경되어 읽지 못했습니다. 잠시 후 다시 시도하세요.',
    // Sync service
    accountChangedDuringSync: '동기화 중 Google 계정 연결이 바뀌어 이전 결과를 적용하지 않았습니다.',
    syncFileInvalid: 'Google Drive의 동기화 파일이 유효한 ResearchPDF 문서가 아닙니다.',
    syncFileTooNew: 'Google Drive의 동기화 파일을 이 버전에서 읽을 수 없습니다.',
    connectAccountFirst: '설정에서 Google 계정을 먼저 연결하세요.',
    syncTurnedOff: '클라우드 동기화가 꺼져 있습니다.',
    syncFailed: '클라우드 동기화에 실패했습니다.',
    syncConflict: '다른 기기와 동시에 동기화되어 충돌했습니다. 다시 시도하세요.',
  },
  en: {
    badRequest: 'Invalid request.',
    badSyncStatusRequest: 'Invalid sync status request.',
    badSyncRequest: 'Invalid sync request.',
    badConnectRequest: 'Invalid Google connect request.',
    badDisconnectRequest: 'Invalid Google disconnect request.',
    badSyncSettingRequest: 'Invalid sync settings request.',
    badSyncHint: 'Invalid sync hint.',
    badLibraryRequest: 'Invalid library request.',
    badOpenDefaultViewerRequest: 'Invalid request to open in the default PDF viewer.',
    badPdfTabRequest: 'Invalid PDF tab request.',
    badPdfTabState: 'Invalid PDF tab state.',
    badProjectRequest: 'Invalid project request.',
    badOpenProjectRequest: 'Invalid request to open a project.',
    badMoveProjectRequest: 'Invalid request to move to a project.',
    badRestoreTabsRequest: 'Invalid request to restore viewer tabs.',
    badSyncWebRoutingRequest: 'Invalid request to sync web PDF routing.',
    tabNotFound: 'Couldn’t find the tab.',
    noSuchProject: 'That project doesn’t exist.',
    fileAccessOff: 'File URL access is turned off, so it can’t switch to the local file.',
    authBadResponse: 'Unexpected response from Google sign-in.',
    authVerifyFailed: 'Couldn’t verify the Google sign-in response.',
    authExpired: 'Google sign-in expired. Reconnect your Google account in settings.',
    authDenied: 'Access to the Google account wasn’t allowed.',
    authFailed: 'Google sign-in failed.',
    authDriveDenied: 'Access to Google Drive app data wasn’t granted.',
    authServerUnreachable: 'Couldn’t reach Google’s authentication server.',
    tokenVerifyFailed: 'Couldn’t verify the Google token.',
    syncNotConfigured: 'Google sync isn’t set up in this build.',
    authCancelled: 'Google sign-in was cancelled.',
    accountMismatch: 'You’re signed in with a different account than the connected Google account. Reconnect in settings.',
    driveFileTooLarge: 'The sync file on Google Drive is too large.',
    driveReadFailed: 'Couldn’t read the sync file on Google Drive.',
    driveQuotaExceeded: 'Google Drive is out of storage.',
    driveRateLimited: 'Google Drive request limit exceeded. Try again in a moment.',
    driveDenied: 'Google Drive access was denied.',
    driveHttpError: (status: number) => `Google Drive request failed (HTTP ${status}).`,
    driveBadUrl: 'Invalid Google Drive request URL.',
    syncTimeout: 'The sync request timed out.',
    driveUnreachable: 'Couldn’t connect to Google Drive.',
    driveBadResponse: 'Couldn’t parse the Google Drive response.',
    driveUploadSessionFailed: 'Couldn’t open a Google Drive upload session.',
    driveUploadUnverified: 'Couldn’t confirm the Google Drive upload result.',
    accountInfoFailed: 'Couldn’t verify the Google account info.',
    driveFileChanging: 'The Google Drive file kept changing, so it couldn’t be read. Try again in a moment.',
    accountChangedDuringSync: 'The Google account connection changed during sync, so the earlier result wasn’t applied.',
    syncFileInvalid: 'The sync file on Google Drive isn’t a valid ResearchPDF document.',
    syncFileTooNew: 'This version can’t read the sync file on Google Drive.',
    connectAccountFirst: 'Connect a Google account in settings first.',
    syncTurnedOff: 'Cloud sync is turned off.',
    syncFailed: 'Cloud sync failed.',
    syncConflict: 'Another device synced at the same time and caused a conflict. Try again.',
  },
});
