// PDF hub strings (pdf-hub.html, pdfHub.ts).
import { messages } from '../shared/i18n';

export const S = messages({
  ko: {
    // Strip and static page
    stripAria: '열린 PDF',
    home: '홈',
    homeLibrary: '홈 · 라이브러리',
    openPdfFile: 'PDF 파일 열기',
    moveToOtherProject: '다른 프로젝트로 이동',
    moveToProject: '프로젝트로 이동',
    settings: '설정',
    allTabsRecent: '모든 탭 · 최근 닫은 탭',
    allTabs: '모든 탭',
    findOpenTabs: '열린 탭 찾기',
    projects: '프로젝트',
    newProjectPlaceholder: '새 프로젝트 — 이름 입력 후 Enter',
    newFolderTitle: '입력한 이름으로 새 폴더 만들기',
    newFolderAria: '새 폴더 만들기',
    moveNewPlaceholder: '새 프로젝트로 이동 — 이름 입력 후 Enter',
    projectIcon: '프로젝트 아이콘',
    backToProjects: '프로젝트 목록으로',
    iconLabel: '아이콘',
    emojiLabel: '이모지',
    colorLabel: '색',
    emojiPlaceholder: '다른 이모지 입력·붙여넣기',
    styleReset: '기본으로 (첫 글자)',
    done: '완료',
    searchLibraryPlaceholder: '열었던 PDF 찾기 — 제목, 파일 이름, 주소',
    openFile: '파일 열기…',

    // Tabs
    projectFallback: '프로젝트',
    close: '닫기',
    closeShortcut: '닫기 (Alt+W)',
    closePdf: '이 PDF 닫기',
    closeAria: (name: string) => `${name} 닫기`,
    pinnedTip: '고정됨 · 우클릭해 고정 해제',
    tooManyDocs: (n: number) => `한 프로젝트에는 PDF를 ${n}개까지 열 수 있습니다.`,
    pinnedCantClose: '고정된 탭입니다. 우클릭해 고정을 해제하면 닫을 수 있습니다.',
    tabClosed: '탭을 닫았습니다.',
    undo: '되돌리기',
    undoShortcut: '되돌리기 (Alt+Shift+T)',
    inOtherProject: (name: string) => `‘${name}’ 프로젝트의 문서입니다. 기본 프로젝트로 옮긴 뒤 고정하세요.`,
    localPinNote: '로컬 파일은 홈의 고정 목록에만 표시됩니다.',
    pinAfterLoad: '문서를 불러온 뒤 고정합니다.',
    nothingToReopen: '다시 열 탭이 없습니다.',
    mergedIntoTab: '이미 열려 있는 문서라 그 탭으로 합쳤습니다.',
    localReselect: '컴퓨터의 파일에서 연 PDF입니다. 파일을 다시 선택하세요.',
    localFile: '로컬 파일',

    // All-tabs list
    noMatchingTab: '일치하는 탭이 없습니다.',
    noOpenTabs: '열린 탭이 없습니다.',
    closedDocsOf: (name: string) => `${name}의 닫힌 문서`,
    openedAgo: (when: string) => `${when} 열어 봄`,
    closedAgo: (when: string) => `${when} 닫음`,
    recentlyClosed: '최근 닫은 탭',

    // Tab menu
    pin: '고정',
    unpin: '고정 해제',
    moveToProjectDots: '프로젝트로 이동…',
    kindMenuItem: (kind: string) => `문서 종류: ${kind}…`,
    removeFromProject: '프로젝트에서 빼기',
    copyUrl: '주소 복사',
    urlCopied: '주소를 복사했습니다.',
    urlCopyFailed: '주소를 복사하지 못했습니다.',
    closeOthers: '다른 탭 모두 닫기',

    // Home: filters, sort, rows
    filterAll: '전체',
    filterAnnotated: '필기 있음',
    filterReading: '읽는 중',
    filterUnread: '안 읽음',
    sortRecent: '최근 연 순',
    sortTitle: '제목 순',
    sortYear: '최신 연도 순',
    sortProgress: '많이 읽은 순',
    filterAria: '거르기',
    sortAria: '정렬',
    selectAria: (name: string) => `${name} 선택`,
    pageOf: (page: number, total: number) => `${page} / ${total}쪽`,
    pages: (n: number) => `${n}쪽`,
    hasAnnotations: '필기 있음',
    badgeOpen: '열림',
    addToProjectTitle: (project: string) => `${project}에 추가`,
    addToProjectAria: (name: string, project: string) => `${name}을(를) ${project}에 추가`,
    addedTo: (project: string) => `${project}에 추가했습니다.`,
    pinTitle: '고정 — 이 프로젝트의 탭 왼쪽에 둡니다',
    pinAria: (name: string) => `${name} 고정`,
    unpinAria: (name: string) => `${name} 고정 해제`,
    more: '더 보기',
    moreFor: (name: string) => `${name} 더 보기`,
    rowActionAria: (subject: string, label: string) => `${subject} ${label}`,
    showMore: (n: number) => `더 보기 (${n}개 더)`,
    searchResults: (n: number) => `검색 결과 ${n}개`,
    noMatchingPdf: '일치하는 PDF가 없습니다.',
    dragToReorder: '끌어서 순서 변경 · 탭 줄 순서와 같음',
    pinnedHeading: '고정',
    documents: '문서',
    noMatchFilter: '이 조건에 맞는 문서가 없습니다.',
    emptyDefault: '아직 연 PDF가 없습니다. 웹에서 PDF를 열거나, 파일을 이 창에 끌어다 놓으세요. 처음 연 PDF는 기본 프로젝트에 모이고, 위의 ‘프로젝트로 이동’으로 다른 프로젝트에 옮길 수 있습니다.',
    emptyProject: '아직 문서가 없습니다. 아래 목록에서 열거나 +로 추가하고, 다른 프로젝트의 탭에서는 ‘프로젝트로 이동’을 쓰세요. 이 프로젝트에서 연 PDF는 자동으로 추가됩니다.',
    projectDocs: '이 프로젝트의 문서',
    otherPdfs: '다른 PDF',

    // Document kinds
    kindJournal: '저널 논문',
    kindConference: '학회 논문',
    kindPreprint: '프리프린트',
    kindSurvey: '서베이·리뷰',
    kindTechnical: '보고서·학위논문',
    kindDocument: '일반 PDF',
    kindMenuHeading: '문서 종류',
    kindAuto: (kind: string) => `자동 — ${kind}`,

    // Document menus and selection bar
    open: '열기',
    docsOne: (name: string) => `‘${name}’`,
    docsMany: (n: number) => `${n}개 문서`,
    addedDocsTo: (docs: string, project: string) => `${docs}를 ${project}에도 추가했습니다.`,
    movedDocs: (n: number, project: string) => `${n}개 문서를 ${project}(으)로 옮겼습니다.`,
    nothingToMove: '옮길 문서가 없습니다.',
    removedDocs: (docs: string) => `${docs}를 이 프로젝트에서 뺐습니다.`,
    addToAnother: '다른 프로젝트에도 추가',
    moveToAnother: '다른 프로젝트로 옮기기',
    alreadyHas: (project: string) => `${project} — 이미 있음`,
    noOtherProjects: '다른 프로젝트가 없습니다',
    removeFromThisProject: '이 프로젝트에서 빼기',
    selectionAria: '선택한 문서',
    selectedCount: (n: number) => `${n}개 선택`,
    moveShort: '옮기기',
    clearSelection: '선택 해제',

    // Projects list
    projectBtnTitle: (name: string) => `프로젝트: ${name} — 다른 프로젝트 열기, 새로 만들기`,
    projectBtnAria: (name: string) => `프로젝트 ${name}`,
    projectCreateFailed: '프로젝트를 만들지 못했습니다.',
    projectOpenFailed: '프로젝트를 열지 못했습니다.',
    viewingNow: '지금 보는 중',
    stateOpen: '열림',
    stateClosed: '닫힘',
    docCount: (n: number) => `문서 ${n}개`,
    openInNewTab: '새 탭에서 열기',
    folderProjectCount: (n: number) => `프로젝트 ${n}개`,
    folderEmpty: '비어 있음 — 프로젝트를 끌어다 넣으세요',
    expand: '펼치기',
    collapse: '접기',
    changeStyle: '아이콘·색 바꾸기…',
    rename: '이름 바꾸기',
    projectNameLabel: '프로젝트 이름',
    folderNameLabel: '폴더 이름',
    moveToFolderHeading: '폴더로 옮기기',
    outOfFolder: '폴더 밖으로',
    newFolderWithProject: '새 폴더 만들어 넣기…',
    delete: '삭제',
    confirmDeleteProject: (name: string) => `‘${name}’ 프로젝트를 삭제할까요?\n\n문서와 필기는 지워지지 않습니다. 다른 프로젝트에 없는 문서는 기본 프로젝트로 돌아갑니다.`,
    deleteFolder: '폴더 삭제 (프로젝트는 남김)',
    folderDeleted: (name: string) => `‘${name}’ 폴더를 지웠습니다. 안의 프로젝트는 목록에 그대로 있습니다.`,
    folderCreateFailed: '폴더를 만들지 못했습니다.',
    newFolderPrompt: '새 폴더 이름',
    folderNameNeeded: '폴더 이름을 입력한 뒤 폴더 버튼을 누르세요.',
    enterEmoji: '이모지 하나를 입력하세요.',

    // Move popover
    moveTitle: (name: string) => `‘${name}’ 옮기기`,
    thisProject: '지금 이 프로젝트',
    alreadyIn: '이미 들어 있음',
    alreadyInTitle: '이 문서가 이미 들어 있는 프로젝트입니다',
    moveToThisProject: '이 프로젝트로 옮기기',
    alsoAddTitle: '여기에도 추가 (지금 프로젝트에도 남김)',
    alsoAddAria: (project: string) => `${project}에도 추가`,
    noProjectsToMove: '옮길 다른 프로젝트가 없습니다. 아래에서 새로 만드세요.',
    loadThenMove: '문서를 불러온 뒤 옮깁니다.',
    moveFailed: '옮기지 못했습니다.',
    alsoAddedTo: (name: string) => `${name}에도 추가했습니다.`,
    movedTo: (name: string) => `${name}(으)로 옮겼습니다.`,
    movedToLocal: (name: string) => `${name}(으)로 옮겼습니다. 로컬 파일은 그 프로젝트에서 다시 열어야 합니다.`,
    removedFromProject: '이 프로젝트에서 뺐습니다.',
    projectDeleted: '프로젝트가 삭제되어 이 탭은 기본 프로젝트가 되었습니다.',
    movedToPdfTab: 'PDF 탭으로 옮겼습니다.',
  },
  en: {
    // Strip and static page
    stripAria: 'Open PDFs',
    home: 'Home',
    homeLibrary: 'Home · Library',
    openPdfFile: 'Open a PDF file',
    moveToOtherProject: 'Move to another project',
    moveToProject: 'Move to project',
    settings: 'Settings',
    allTabsRecent: 'All tabs · Recently closed',
    allTabs: 'All tabs',
    findOpenTabs: 'Find open tabs',
    projects: 'Projects',
    newProjectPlaceholder: 'New project — type a name, then press Enter',
    newFolderTitle: 'Create a new folder with the typed name',
    newFolderAria: 'New folder',
    moveNewPlaceholder: 'Move to a new project — type a name, then press Enter',
    projectIcon: 'Project icon',
    backToProjects: 'Back to projects',
    iconLabel: 'Icon',
    emojiLabel: 'Emoji',
    colorLabel: 'Color',
    emojiPlaceholder: 'Type or paste another emoji',
    styleReset: 'Reset (first letter)',
    done: 'Done',
    searchLibraryPlaceholder: 'Find a PDF you’ve opened — title, file name, URL',
    openFile: 'Open file…',

    // Tabs
    projectFallback: 'Project',
    close: 'Close',
    closeShortcut: 'Close (Alt+W)',
    closePdf: 'Close this PDF',
    closeAria: (name: string) => `Close ${name}`,
    pinnedTip: 'Pinned · right-click to unpin',
    tooManyDocs: (n: number) => `A project can have up to ${n} PDFs open.`,
    pinnedCantClose: 'This tab is pinned. Right-click it to unpin it before closing.',
    tabClosed: 'Tab closed.',
    undo: 'Undo',
    undoShortcut: 'Undo (Alt+Shift+T)',
    inOtherProject: (name: string) => `This document belongs to the “${name}” project. Move it to the default project, then pin it.`,
    localPinNote: 'Local files appear only in the pinned list on Home.',
    pinAfterLoad: 'The document will be pinned once it loads.',
    nothingToReopen: 'No tab to reopen.',
    mergedIntoTab: 'That document was already open, so it was merged into its tab.',
    localReselect: 'This PDF was opened from a file on your computer. Choose the file again.',
    localFile: 'Local file',

    // All-tabs list
    noMatchingTab: 'No matching tabs.',
    noOpenTabs: 'No open tabs.',
    closedDocsOf: (name: string) => `Closed documents in ${name}`,
    openedAgo: (when: string) => `Opened ${when}`,
    closedAgo: (when: string) => `Closed ${when}`,
    recentlyClosed: 'Recently closed',

    // Tab menu
    pin: 'Pin',
    unpin: 'Unpin',
    moveToProjectDots: 'Move to project…',
    kindMenuItem: (kind: string) => `Document type: ${kind}…`,
    removeFromProject: 'Remove from this project',
    copyUrl: 'Copy URL',
    urlCopied: 'URL copied.',
    urlCopyFailed: 'Couldn’t copy the URL.',
    closeOthers: 'Close other tabs',

    // Home: filters, sort, rows
    filterAll: 'All',
    filterAnnotated: 'Annotated',
    filterReading: 'Reading',
    filterUnread: 'Unread',
    sortRecent: 'Recently opened',
    sortTitle: 'Title',
    sortYear: 'Newest year',
    sortProgress: 'Most read',
    filterAria: 'Filter',
    sortAria: 'Sort',
    selectAria: (name: string) => `Select ${name}`,
    pageOf: (page: number, total: number) => `Page ${page} of ${total}`,
    pages: (n: number) => `${n} page${n === 1 ? '' : 's'}`,
    hasAnnotations: 'Has annotations',
    badgeOpen: 'Open',
    addToProjectTitle: (project: string) => `Add to ${project}`,
    addToProjectAria: (name: string, project: string) => `Add ${name} to ${project}`,
    addedTo: (project: string) => `Added to ${project}.`,
    pinTitle: 'Pin — keeps it at the left of this project’s tabs',
    pinAria: (name: string) => `Pin ${name}`,
    unpinAria: (name: string) => `Unpin ${name}`,
    more: 'More actions',
    moreFor: (name: string) => `More actions for ${name}`,
    rowActionAria: (subject: string, label: string) => `${label}: ${subject}`,
    showMore: (n: number) => `Show ${n} more`,
    searchResults: (n: number) => `Search results (${n})`,
    noMatchingPdf: 'No matching PDFs.',
    dragToReorder: 'Drag to reorder · same order as the tab strip',
    pinnedHeading: 'Pinned',
    documents: 'Documents',
    noMatchFilter: 'No documents match this filter.',
    emptyDefault: 'No PDFs opened yet. Open a PDF on the web, or drag a file into this window. The first PDFs you open collect in the default project; use “Move to project” above to move them to another project.',
    emptyProject: 'No documents yet. Open one from the list below or add it with +, or use “Move to project” on a tab in another project. PDFs you open in this project are added automatically.',
    projectDocs: 'Documents in this project',
    otherPdfs: 'Other PDFs',

    // Document kinds
    kindJournal: 'Journal article',
    kindConference: 'Conference paper',
    kindPreprint: 'Preprint',
    kindSurvey: 'Survey/review',
    kindTechnical: 'Report/thesis',
    kindDocument: 'Plain PDF',
    kindMenuHeading: 'Document type',
    kindAuto: (kind: string) => `Automatic — ${kind}`,

    // Document menus and selection bar
    open: 'Open',
    docsOne: (name: string) => `“${name}”`,
    docsMany: (n: number) => `${n} documents`,
    addedDocsTo: (docs: string, project: string) => `Added ${docs} to ${project}.`,
    movedDocs: (n: number, project: string) => `Moved ${n} document${n === 1 ? '' : 's'} to ${project}.`,
    nothingToMove: 'No documents to move.',
    removedDocs: (docs: string) => `Removed ${docs} from this project.`,
    addToAnother: 'Add to another project',
    moveToAnother: 'Move to another project',
    alreadyHas: (project: string) => `${project} — already added`,
    noOtherProjects: 'No other projects',
    removeFromThisProject: 'Remove from this project',
    selectionAria: 'Selected documents',
    selectedCount: (n: number) => `${n} selected`,
    moveShort: 'Move',
    clearSelection: 'Clear selection',

    // Projects list
    projectBtnTitle: (name: string) => `Project: ${name} — open another project or create one`,
    projectBtnAria: (name: string) => `Project ${name}`,
    projectCreateFailed: 'Couldn’t create the project.',
    projectOpenFailed: 'Couldn’t open the project.',
    viewingNow: 'Viewing now',
    stateOpen: 'Open',
    stateClosed: 'Closed',
    docCount: (n: number) => `${n} document${n === 1 ? '' : 's'}`,
    openInNewTab: 'Open in new tab',
    folderProjectCount: (n: number) => `${n} project${n === 1 ? '' : 's'}`,
    folderEmpty: 'Empty — drag projects here',
    expand: 'Expand',
    collapse: 'Collapse',
    changeStyle: 'Change icon and color…',
    rename: 'Rename',
    projectNameLabel: 'Project name',
    folderNameLabel: 'Folder name',
    moveToFolderHeading: 'Move to folder',
    outOfFolder: 'Move out of folder',
    newFolderWithProject: 'New folder with this project…',
    delete: 'Delete',
    confirmDeleteProject: (name: string) => `Delete the project “${name}”?\n\nYour documents and annotations won’t be deleted. Documents that aren’t in another project go back to the default project.`,
    deleteFolder: 'Delete folder (keep projects)',
    folderDeleted: (name: string) => `Folder “${name}” deleted. The projects inside are still in the list.`,
    folderCreateFailed: 'Couldn’t create the folder.',
    newFolderPrompt: 'New folder name',
    folderNameNeeded: 'Enter a folder name, then press the folder button.',
    enterEmoji: 'Enter a single emoji.',

    // Move popover
    moveTitle: (name: string) => `Move “${name}”`,
    thisProject: 'This project',
    alreadyIn: 'Already in it',
    alreadyInTitle: 'This document is already in this project',
    moveToThisProject: 'Move to this project',
    alsoAddTitle: 'Also add here (keep it in the current project too)',
    alsoAddAria: (project: string) => `Also add to ${project}`,
    noProjectsToMove: 'No other projects to move to. Create one below.',
    loadThenMove: 'The document will be moved once it loads.',
    moveFailed: 'Couldn’t move it.',
    alsoAddedTo: (name: string) => `Also added to ${name}.`,
    movedTo: (name: string) => `Moved to ${name}.`,
    movedToLocal: (name: string) => `Moved to ${name}. Local files have to be reopened in that project.`,
    removedFromProject: 'Removed from this project.',
    projectDeleted: 'The project was deleted, so this tab is now in the default project.',
    movedToPdfTab: 'Moved to the PDF tab.',
  },
});
