// PDF viewer page strings (pdf-viewer.html, pdfViewer.ts).
import { messages } from '../shared/i18n';

export const S = messages({
  ko: {
    toolbar: 'PDF 도구 모음',
    sidebarTitle: '사이드바 (썸네일·목차)',
    sidebarAria: '사이드바 열기/닫기',
    currentPage: '현재 페이지',
    zoomOutTitle: '축소 (Ctrl+-)',
    zoomOut: '축소',
    zoomAria: '확대/축소',
    zoomAuto: '자동',
    zoomPageFit: '페이지 맞춤',
    zoomPageWidth: '너비 맞춤',
    zoomActual: '실제 크기',
    zoomCustom: '사용자 지정',
    zoomInTitle: '확대 (Ctrl++)',
    zoomIn: '확대',
    fitToggle: '페이지 맞춤 / 너비 맞춤 전환',
    fitToWidth: '너비에 맞춤',
    fitToPage: '페이지에 맞춤',
    rotateTitle: '시계 방향 회전 (Ctrl+])',
    rotate: '시계 방향 회전',
    annotateTitle: '주석 달기',
    annotateAria: '주석 도구 열기/닫기',
    undoTitle: '실행취소 (Ctrl+Z)',
    undo: '실행취소',
    redoTitle: '다시실행 (Ctrl+Y)',
    redo: '다시실행',
    captureAria: '그림·표 영역 복사',
    captureTitle: (shortcut: string) => `그림 복사 (${shortcut} · S) — 한 번: 직접 지정 · 두 번: 그림·표 자동 인식 · 세 번: 끄기 · 언제든 Alt+드래그`,
    findTitle: '문서에서 찾기 (Ctrl+F)',
    find: '찾기',
    downloadTitle: '다운로드 (Ctrl+S)',
    download: '다운로드',
    printTitle: '인쇄 (Ctrl+P)',
    print: '인쇄',
    more: '더보기',
    moreAria: '더보기 메뉴',
    twoPage: '두 페이지 보기',
    showAnnotations: '주석 표시',
    rotateCcw: '시계 반대 방향 회전',
    firstPage: '첫 페이지',
    lastPage: '마지막 페이지',
    presentation: '프레젠테이션',
    properties: '문서 속성…',
    propertiesTitle: '문서 속성',
    openFile: '파일 열기…',
    openNative: 'Chrome 기본 뷰어로 열기',
    paperInfo: '논문 정보',
    reparseTitle: '논문 정보 다시 파싱 (캐시 무시)',
    reparse: '논문 정보 다시 파싱',
    hidePaperInfo: '논문 정보 숨기기',
    findPlaceholder: '문서에서 찾기',
    findPrevTitle: '이전 결과 (Shift+Enter)',
    findPrev: '이전 결과',
    findNextTitle: '다음 결과 (Enter)',
    findNext: '다음 결과',
    matchCase: '대소문자 구분',
    wholeWord: '단어 단위',
    closeTitle: '닫기 (Esc)',
    findClose: '찾기 닫기',
    searching: '검색 중…',
    noMatches: '없음',
    annotateBar: '주석 도구',
    highlighter: '형광펜',
    pen: '펜',
    text: '텍스트',
    color: '색상',
    thickness: '굵기',
    opacity: '투명도',
    deleteSelectedTitle: '선택한 주석 삭제 (Delete)',
    deleteSelected: '선택한 주석 삭제',
    annotateHint: '주석은 다운로드한 PDF에 함께 저장됩니다.',
    thumbnails: '썸네일',
    outline: '목차',
    attachments: '첨부파일',
    dropHint: 'PDF 파일을 여기에 놓으면 엽니다',
    passwordTitle: '암호로 보호된 PDF',
    passwordPrompt: '이 문서를 열려면 암호를 입력하세요.',
    passwordWrong: '암호가 올바르지 않습니다. 다시 입력하세요.',
    passwordAria: 'PDF 암호',
    cancel: '취소',
    open: '열기',
    close: '닫기',
    conflictTitle: '필기가 두 곳에 있습니다',
    keepFile: '파일 필기만 유지',
    keepBrowser: '브라우저 필기만 유지',
    keepBoth: '모두 유지',
    pickManually: '직접 선택…',
    pickHint: '체크한 필기만 남습니다. 항목 위에 마우스를 올리면 문서에서 위치를 보여 줍니다.',
    fileOnly: '파일에만 있는 필기',
    browserOnly: '브라우저에만 있는 필기',
    selectAll: '전체 선택',
    selectNone: '전체 해제',
    back: '뒤로',
    keepSelected: '선택한 필기만 유지',
    printPreparing: '인쇄 준비 중…',
    noOpenPdf: '열린 PDF가 없습니다.',
    downloadFailed: (message: string) => `다운로드하지 못했습니다: ${message}`,
    openNativeFailed: '기본 뷰어로 열지 못했습니다. 설정에서 PDF 뷰어 옵션을 끄고 다시 시도하세요.',
    pdfOnly: 'PDF 파일만 열 수 있습니다.',
    passwordCancelled: '암호를 입력하지 않아 문서를 열 수 없습니다.',
    changedElsewhere: '다른 기기에서 이 문서의 필기나 읽던 위치가 바뀌었습니다.',
    reload: '다시 불러오기',
    reloadFailed: (message: string) => `문서를 다시 불러오지 못했습니다: ${message}`,
    openFailed: (message: string) => `PDF를 열지 못했습니다: ${message}`,
    newVersion: '서버에 이 PDF의 새 버전이 있습니다.',
    openNewVersion: '새 버전 열기',
    noSiteAccess: (app: string) => `${app}가 이 사이트에서 PDF를 받아올 권한이 없습니다. 권한을 허용하면 이 탭을 다시 불러옵니다.`,
    allowSiteAccess: '사이트 접근 권한 허용',
    noFileAccess: (app: string) => `${app}가 로컬 파일을 읽을 수 없습니다. 확장 프로그램 설정에서 "파일 URL에 대한 액세스 허용"을 켠 뒤 이 탭을 새로고침하세요.`,
    openExtensionSettings: '확장 프로그램 설정 열기',
    openNativeAction: '기본 뷰어로 열기',
    noPdfSpecified: '열 PDF가 지정되지 않았습니다. PDF 파일을 이 창에 끌어다 놓거나 메뉴에서 "파일 열기…"를 선택하세요.',
    openingInTab: 'PDF 탭으로 여는 중…',
  },
  en: {
    toolbar: 'PDF toolbar',
    sidebarTitle: 'Sidebar (thumbnails, outline)',
    sidebarAria: 'Show or hide sidebar',
    currentPage: 'Current page',
    zoomOutTitle: 'Zoom out (Ctrl+-)',
    zoomOut: 'Zoom out',
    zoomAria: 'Zoom',
    zoomAuto: 'Automatic',
    zoomPageFit: 'Page fit',
    zoomPageWidth: 'Page width',
    zoomActual: 'Actual size',
    zoomCustom: 'Custom',
    zoomInTitle: 'Zoom in (Ctrl++)',
    zoomIn: 'Zoom in',
    fitToggle: 'Switch between page fit and page width',
    fitToWidth: 'Fit to page width',
    fitToPage: 'Fit to page',
    rotateTitle: 'Rotate clockwise (Ctrl+])',
    rotate: 'Rotate clockwise',
    annotateTitle: 'Annotate',
    annotateAria: 'Show or hide annotation tools',
    undoTitle: 'Undo (Ctrl+Z)',
    undo: 'Undo',
    redoTitle: 'Redo (Ctrl+Y)',
    redo: 'Redo',
    captureAria: 'Copy figure or table area',
    captureTitle: (shortcut: string) => `Copy figure (${shortcut} · S) — once: select manually · twice: detect figures and tables · three times: off · Alt+drag anytime`,
    findTitle: 'Find in document (Ctrl+F)',
    find: 'Find',
    downloadTitle: 'Download (Ctrl+S)',
    download: 'Download',
    printTitle: 'Print (Ctrl+P)',
    print: 'Print',
    more: 'More',
    moreAria: 'More menu',
    twoPage: 'Two-page view',
    showAnnotations: 'Show annotations',
    rotateCcw: 'Rotate counterclockwise',
    firstPage: 'First page',
    lastPage: 'Last page',
    presentation: 'Presentation',
    properties: 'Document properties…',
    propertiesTitle: 'Document properties',
    openFile: 'Open file…',
    openNative: 'Open in Chrome’s viewer',
    paperInfo: 'Paper info',
    reparseTitle: 'Re-parse paper info (ignore cache)',
    reparse: 'Re-parse paper info',
    hidePaperInfo: 'Hide paper info',
    findPlaceholder: 'Find in document',
    findPrevTitle: 'Previous result (Shift+Enter)',
    findPrev: 'Previous result',
    findNextTitle: 'Next result (Enter)',
    findNext: 'Next result',
    matchCase: 'Match case',
    wholeWord: 'Whole words',
    closeTitle: 'Close (Esc)',
    findClose: 'Close find bar',
    searching: 'Searching…',
    noMatches: 'No results',
    annotateBar: 'Annotation tools',
    highlighter: 'Highlighter',
    pen: 'Pen',
    text: 'Text',
    color: 'Color',
    thickness: 'Thickness',
    opacity: 'Opacity',
    deleteSelectedTitle: 'Delete selected annotation (Delete)',
    deleteSelected: 'Delete selected annotation',
    annotateHint: 'Annotations are saved in the PDF when you download it.',
    thumbnails: 'Thumbnails',
    outline: 'Outline',
    attachments: 'Attachments',
    dropHint: 'Drop a PDF file here to open it',
    passwordTitle: 'Password-protected PDF',
    passwordPrompt: 'Enter the password to open this document.',
    passwordWrong: 'Incorrect password. Try again.',
    passwordAria: 'PDF password',
    cancel: 'Cancel',
    open: 'Open',
    close: 'Close',
    conflictTitle: 'Annotations exist in two places',
    keepFile: 'Keep file annotations only',
    keepBrowser: 'Keep browser annotations only',
    keepBoth: 'Keep both',
    pickManually: 'Choose…',
    pickHint: 'Only checked annotations are kept. Hover over an item to see where it is in the document.',
    fileOnly: 'Only in the file',
    browserOnly: 'Only in the browser',
    selectAll: 'Select all',
    selectNone: 'Select none',
    back: 'Back',
    keepSelected: 'Keep selected annotations',
    printPreparing: 'Preparing to print…',
    noOpenPdf: 'No PDF is open.',
    downloadFailed: (message: string) => `Couldn’t download: ${message}`,
    openNativeFailed: 'Couldn’t open in Chrome’s viewer. Turn off the PDF viewer option in settings and try again.',
    pdfOnly: 'Only PDF files can be opened.',
    passwordCancelled: 'No password was entered, so the document can’t be opened.',
    changedElsewhere: 'Annotations or your reading position for this document changed on another device.',
    reload: 'Reload',
    reloadFailed: (message: string) => `Couldn’t reload the document: ${message}`,
    openFailed: (message: string) => `Couldn’t open the PDF: ${message}`,
    newVersion: 'A newer version of this PDF is available on the server.',
    openNewVersion: 'Open new version',
    noSiteAccess: (app: string) => `${app} doesn’t have permission to fetch the PDF from this site. If you allow it, this tab will reload.`,
    allowSiteAccess: 'Allow site access',
    noFileAccess: (app: string) => `${app} can’t read local files. Turn on “Allow access to file URLs” in the extension’s settings, then reload this tab.`,
    openExtensionSettings: 'Open extension settings',
    openNativeAction: 'Open in Chrome’s viewer',
    noPdfSpecified: 'No PDF to open was specified. Drag a PDF file into this window, or choose “Open file…” from the menu.',
    openingInTab: 'Opening in a PDF tab…',
  },
});
