// Popup strings (popup.html, popup.ts).
import { messages } from '../shared/i18n';

export const S = messages({
  ko: {
    tagline: '논문 PDF 뷰어 · 필기와 읽던 위치가 따라옵니다',
    openPdfTab: 'PDF 탭 열기',
    syncTitle: 'Google Drive 동기화',
    loading: '불러오는 중…',
    webHint: '웹 PDF는 아직 Chrome 기본 뷰어로 열립니다.',
    webHintOpen: '설정에서 켜기',
    settings: '설정',
    statusFailed: '상태를 불러오지 못했습니다.',
    syncNow: '지금 동기화',
    turnOn: '켜기',
    connect: '연결',
    notConnected: '연결하면 필기와 읽던 위치가 모든 기기를 따라옵니다.',
    googleAccount: 'Google 계정',
    off: (account: string) => `${account} · 꺼져 있음`,
    syncing: '동기화 중…',
    error: (message: string) => `오류: ${message}`,
    lastSync: (account: string, when: string) => `${account} · ${when}`,
    waitingFirst: (account: string) => `${account} · 첫 동기화를 기다리는 중`,
    syncFailed: '동기화에 실패했습니다.',
  },
  en: {
    tagline: 'PDF viewer for papers · your notes and place follow you',
    openPdfTab: 'Open PDF tab',
    syncTitle: 'Google Drive sync',
    loading: 'Loading…',
    webHint: 'Web PDFs still open in Chrome’s own viewer.',
    webHintOpen: 'Turn on in settings',
    settings: 'Settings',
    statusFailed: 'Couldn’t load the status.',
    syncNow: 'Sync now',
    turnOn: 'Turn on',
    connect: 'Connect',
    notConnected: 'Connect to have your notes and place follow you to every device.',
    googleAccount: 'Google account',
    off: (account: string) => `${account} · off`,
    syncing: 'Syncing…',
    error: (message: string) => `Error: ${message}`,
    lastSync: (account: string, when: string) => `${account} · ${when}`,
    waitingFirst: (account: string) => `${account} · waiting for the first sync`,
    syncFailed: 'Sync failed.',
  },
});
