// Settings page strings (settings.html, settings.ts).
import { messages } from '../shared/i18n';

export const S = messages({
  ko: {
    // ── Page and navigation ──
    pageTitle: '설정 · ResearchPDF',
    settings: '설정',
    searchSettings: '설정 찾기',
    sectionsNav: '설정 섹션',
    chipSync: '동기화',
    chipOpen: 'PDF 열기',
    chipDisplay: '화면',
    chipProjects: '프로젝트',
    chipCapture: '그림 캡처',
    chipPaper: '논문 정보',
    chipStorage: '저장 공간',
    chipKeys: '단축키',
    chipAbout: '정보',
    noMatch: '일치하는 설정이 없습니다.',
    optional: '선택',
    thisDeviceOnly: '이 기기만',

    // ── Sync ──
    syncTitle: 'Google Drive 동기화',
    syncDesc: '필기와 읽던 위치, 열어 본 PDF 목록, 프로젝트를 내 Google Drive의 앱 전용 숨김 폴더에 저장해 모든 Chrome 프로필과 기기에서 이어 봅니다. 이 폴더 밖의 Drive 파일은 볼 수 없고, PDF 파일 자체는 올리지 않습니다.',
    noAccount: '연결된 Google 계정이 없습니다.',
    syncNow: '지금 동기화',
    syncUse: '동기화 사용',
    syncUseSub: '끄면 이 기기는 Drive와 주고받지 않습니다. 계정 연결은 유지됩니다.',
    connectGoogle: 'Google 계정 연결',
    connectOther: '다른 계정으로 연결',
    disconnect: '연결 해제',
    loginTrouble: '로그인이 안 될 때',
    googleAccount: 'Google 계정',
    signInHelp: 'Google 로그인 창이 열리지 않거나 오류로 끝나면, Chrome의 팝업 차단이나 로그인 상태를 확인하고 잠시 뒤 다시 연결해 보세요. 계속 안 되면 아래 "개발자용 정보"를 붙여 문의·버그 제보로 알려 주세요.',
    signInUnavailable: '이 설치본에서는 Google Drive 동기화를 쓸 수 없습니다(Google 로그인 설정이 빠진 빌드). Chrome 웹 스토어의 ResearchPDF를 설치하면 쓸 수 있습니다.',
    devDetails: '개발자용 정보',
    setupConfigured: (uri: string) => `로그인 창에 redirect_uri_mismatch가 뜨면 이 설치의 리디렉션 URI가 OAuth 클라이언트에 등록되지 않은 것입니다: ${uri}`,
    setupMissing: (uri: string) => `이 빌드에는 Google OAuth 클라이언트 ID가 없습니다. docs/google-drive-sync.md를 따라 설정하세요. 등록할 리디렉션 URI: ${uri}`,
    syncing: '동기화 중…',
    syncError: (error: string) => `동기화 오류: ${error}`,
    lastSync: (when: string, pending: boolean) => `마지막 동기화 ${when}${pending ? ' · 보낼 변경 있음' : ''}`,
    waitingFirst: '첫 동기화를 기다리는 중입니다.',
    syncOff: '동기화가 꺼져 있습니다.',
    syncHint: '연결하면 약 15분마다, 그리고 문서를 열고 필기할 때 동기화합니다.',
    syncStatusFailed: '동기화 상태를 불러오지 못했습니다.',
    signInOpening: 'Google 로그인 창을 여는 중…',
    connectFailed: 'Google 계정을 연결하지 못했습니다.',
    confirmAccountChange: (previous: string, next: string) => `이 기기의 논문, 필기, 읽던 위치와 프로젝트는 지금까지 ${previous} 계정의 Google Drive와 동기화했습니다.\n\n${next} 계정으로 연결하면 이 기기의 데이터가 ${next} 계정의 Drive에 더해집니다. ${previous} 계정의 Drive에 있는 데이터는 그대로 남습니다.\n\n${next} 계정으로 연결할까요?`,
    accountChangeDeclined: '연결하지 않았습니다.',
    disconnected: '연결을 해제했습니다. Drive에 저장된 데이터는 그대로 남아 있습니다.',
    disconnectFailed: '연결을 해제하지 못했습니다.',
    confirmDisconnect: (account: string) => `${account} 연결을 해제할까요?\n\n이 기기는 더 이상 Drive와 동기화하지 않습니다. Drive에 저장된 데이터와 이 기기의 필기·읽던 위치는 그대로 남습니다.`,
    syncSwitchFailed: '동기화 설정을 바꾸지 못했습니다.',
    syncFailed: '동기화에 실패했습니다.',

    // ── Opening PDFs ──
    openTitle: 'PDF 열기',
    webPdfTitle: '웹 PDF도 ResearchPDF로 열기',
    webPdfSub: '주소로 연 PDF(https://…)를 내장 뷰어로 엽니다. 켜면 사이트 접근 권한을 요청하며, PDF를 가져와 뷰어로 돌리는 데만 씁니다.',
    localPdfTitle: '컴퓨터의 PDF를 ResearchPDF로 열기',
    localPdfSub: 'file:// 로 연 PDF를 Chrome 기본 뷰어 대신 내장 뷰어로 엽니다. Chrome의 확장 프로그램 세부정보에서 "파일 URL에 대한 액세스 허용"이 켜져 있어야 합니다.',
    fileAccessOpen: 'Chrome에서 켜기',
    hubScopeTitle: 'PDF가 모이는 탭',
    hubScopeSub: '창마다: PDF는 그것을 연 창의 PDF 탭에 모이고, 다른 창을 앞으로 불러오지 않습니다. 창을 여러 개 띄워 쓸 때 편합니다. 브라우저 전체에 하나: 프로젝트마다 PDF 탭이 하나뿐이고, 어느 창에서 열든 그 탭으로 갑니다. 한 창에서 스페이스를 오가는 브라우저(Arc 등)에 맞습니다. 창이 하나면 둘은 같습니다.',
    hubScopeWindow: '창마다 PDF 탭',
    hubScopeBrowser: '브라우저 전체에 하나',
    restoreTitle: '닫힌 PDF 탭 복구',
    restoreSub: '확장 프로그램이 업데이트되면 Chrome이 PDF 탭을 닫습니다. 보통 자동으로 다시 열리며, 안 됐을 때 씁니다.',
    restore: '복구',
    siteAccessOn: '사이트 접근 허용됨',
    siteAccessNeeded: '사이트 접근 필요',
    fileUrlOn: '파일 URL 접근 켜짐',
    fileUrlOff: '파일 URL 접근 꺼짐',
    siteDenied: '사이트 접근 권한이 허용되지 않아 켜지 못했습니다.',
    savedNotApplied: '저장했지만 적용하지 못했습니다. 확장 프로그램을 다시 로드하세요.',
    webOn: '웹 PDF를 ResearchPDF로 엽니다. 이미 열린 PDF 탭은 새로고침하세요.',
    webOff: '웹 PDF는 Chrome 기본 뷰어로 엽니다.',
    localOff: '컴퓨터의 PDF는 Chrome 기본 뷰어로 엽니다.',
    localOn: '컴퓨터의 PDF를 ResearchPDF로 엽니다.',
    localNeedsAccess: '켰습니다. Chrome에서 "파일 URL에 대한 액세스 허용"도 켜야 열립니다.',
    restoreFailed: 'PDF 탭을 복구하지 못했습니다.',
    restoredTabs: (n: number) => `PDF 탭 ${n}개를 다시 열었습니다.`,
    nothingToRestore: (open: number) => `복구할 탭이 없습니다 (열려 있는 PDF 탭 ${open}개).`,
    noTabHistory: '복구할 PDF 탭 기록이 없습니다.',

    // ── Display ──
    displayTitle: '화면',
    languageTitle: '언어 / Language',
    languageSub: '바꾸면 열린 PDF 탭이 새 언어로 다시 열립니다.',
    languageAuto: '자동 (브라우저 언어)',
    languageKo: '한국어',
    languageEn: 'English',
    tabTitle: '탭 제목',
    tabTitleSub: 'PDF 탭 줄의 첫 줄에 보일 이름입니다.',
    tabTitlePaper: '논문 제목 (없으면 PDF 이름)',
    tabTitleDocument: 'PDF 제목·파일 이름',
    tabSubtitle: '탭 부제목',
    tabSubtitleSub: '탭의 둘째 줄입니다. 고정한 탭에는 나오지 않습니다.',
    tabSubtitleVenue: '게재처·연도',
    tabSubtitleOther: '다른 이름 (PDF 이름 또는 논문 제목)',
    tabSubtitleNone: '없음 — 한 줄로',
    kindIcons: '문서 종류 아이콘',
    kindIconsSub: '탭과 홈에서 저널·학회·프리프린트·서베이·보고서를 아이콘으로 구분합니다.',
    kindIconsColor: '색 아이콘',
    kindIconsMono: '아이콘만 (한 색)',
    kindIconsOff: '끄기 — 모두 문서 아이콘',
    projectFavicon: 'Chrome 탭에 프로젝트 아이콘',
    projectFaviconSub: 'PDF 탭의 Chrome 탭 아이콘을 그 프로젝트의 아이콘으로 바꿔, 프로젝트별 탭을 한눈에 구분합니다.',

    // ── Projects ──
    projectsTitle: '프로젝트',
    afterMove: '다른 프로젝트로 옮긴 뒤',
    afterMoveSub: '옮긴 뒤 뜨는 알림에서 되돌리거나 반대쪽으로 갈 수 있습니다.',
    afterMoveStay: '지금 프로젝트에 머물기',
    afterMoveFollow: '옮긴 프로젝트로 따라가기',

    // ── Figure capture ──
    captureTitle: '그림 캡처',
    captureCopy: '캡처하면',
    captureCopySub: '영역을 고르거나 그림·표를 누르면 바로 클립보드에 넣을 것입니다. 나머지는 캡처 옆 패널의 버튼으로 복사합니다.',
    captureCopyNone: '복사 안 함',
    captureCopyImage: '이미지 (슬라이드)',
    captureCopyImageSource: '이미지와 출처 (문서)',
    captureCopySource: '출처만',
    captureEmbed: '이미지 아래에 출처 넣기',
    captureEmbedSub: '복사하거나 저장하는 이미지에 출처 문구를 그려 넣습니다.',
    captureStyle: '출처 형식',
    captureStyleSub: 'APA는 논문 정보 줄의 APA 복사와 같은 문구입니다.',
    captureStyleShort: '짧게',
    captureStyleApa: 'APA 전체',
    capturePrefix: '출처 머리말',
    capturePrefixNone: '없음',
    captureDpi: '해상도',
    captureBackground: '배경',
    captureWhite: '흰색',
    captureTransparent: '투명',
    captureAnnotations: '주석·필기 포함',
    captureAnnotationsSub: '형광펜·펜·텍스트 메모를 이미지에 함께 그립니다.',
    captureAutoDetect: '그림·표 자동 인식',
    captureAutoDetectSub: '캡처 모드에서 보이는 페이지의 그림·표를 찾아 표시합니다. 기기 안의 작은 모델이 페이지마다 돌아갑니다. 끄면 드래그로만 캡처합니다.',
    captureContinuous: '연속 캡처',
    captureContinuousSub: '복사한 뒤에도 캡처 모드를 유지합니다. 끌 때는 S 또는 Esc.',

    // ── Paper info ──
    paperTitle: '논문 정보',
    paperShow: '논문 정보 표시',
    paperShowSub: '논문(DOI·arXiv·제목)을 알아보면 게재처, 인용 수와 추이, 참고문헌, 링크를 보여줍니다. 식별자만 OpenAlex·Crossref·arXiv·Semantic Scholar에 보냅니다.',
    openalexKey: 'OpenAlex API 키',
    openalexKeySub1: '키 없이 쓰면 같은 네트워크(IP)의 모든 사용자가 하루 한도를 나눠 씁니다. 무료 키는 ',
    openalexKeySub2: '에 가입하면 받습니다.',
    s2Key: 'Semantic Scholar API 키',
    s2KeySub1: '키가 없으면 공용 익명 한도를 써서 붐빌 때 인용 수가 빠질 수 있습니다. 키는 ',
    s2KeySub2: '에서 신청합니다.',
    save: '저장',
    remove: '지우기',
    check: '확인',
    offline: '연결하지 못했습니다. 네트워크를 확인하세요.',
    keySaved: '키 저장됨',
    keyNone: '키 없음',
    keyPlaceholderSaved: '저장됨 — 바꾸려면 새 키를 붙여넣고 저장',
    keyPlaceholderEmpty: '키 붙여넣기',
    keySavedNote: '저장했습니다. "확인"으로 동작하는지 볼 수 있습니다.',
    keyRemoved: '키를 지웠습니다.',
    keyEmpty: '붙여넣은 키가 없습니다. 저장한 키를 없애려면 "지우기"를 누르세요.',
    checking: '확인 중…',

    // ── Storage ──
    storageTitle: '저장 공간',
    cacheKeep: '연 PDF를 이 기기에 보관',
    cacheKeepSub: '한 번 연 웹 PDF를 이 기기에 두어, 다시 열 때 네트워크를 기다리지 않습니다. 가끔 서버와 비교해 새 버전이면 알려줍니다. 오래 안 쓴 것부터 지우며 Drive로는 보내지 않습니다.',
    savedPdfs: '보관한 PDF',
    clearSavedPdfs: '보관한 PDF 비우기',
    savedPdfsSize: '보관한 PDF 용량',
    statLibrary: '열어 본 PDF',
    statAnnotated: '필기가 있는 문서',
    statProjects: '프로젝트',
    savedPdfsUsage: (files: number, used: string, max: string) => `보관한 PDF ${files}개 · ${used} / ${max}`,
    noSavedPdfs: '보관한 PDF가 없습니다.',
    usageFailed: '보관 용량을 읽지 못했습니다.',
    countPapers: (n: number) => `${n}편`,
    countProjects: (n: number) => `${n}개`,
    cacheOn: '연 웹 PDF를 이 기기에 보관합니다.',
    cacheOff: '더 이상 보관하지 않습니다. 이미 보관한 PDF는 비우기로 지울 수 있습니다.',
    cacheCleared: '보관한 PDF를 모두 지웠습니다. 필기와 읽던 위치는 그대로입니다.',
    confirmClearCache: (files: number, size: string) => `보관한 PDF ${files}개(${size})를 이 기기에서 지울까요?\n\n다음에 열 때 다시 내려받습니다. 주소가 만료됐거나 로그인해야 받을 수 있는 PDF는 다시 받지 못할 수 있습니다. 필기와 읽던 위치는 그대로입니다.`,

    // ── Shortcuts ──
    keysTitle: '단축키',

    // ── About ──
    aboutTitle: '정보',
    homepage: '홈페이지',
    welcomeAgain: '시작 가이드 다시 보기',
    privacy: '개인정보처리방침',
    feedback: '문의·버그 제보',
    webStore: 'Chrome 웹 스토어',
    gatherTitle: '열려 있는 PDF 모으기',
    gatherSub: 'Chrome 기본 뷰어로 열려 있는 PDF를 이 PDF 탭으로 옮기고 원래 탭을 닫습니다. 확대 배율은 함께 가져오고, 스크롤 위치는 Chrome이 다른 확장에 알려 주지 않아 읽던 위치 기록이 있을 때만 이어집니다.',
    gatherButton: '모으기',
    gatherNone: '모을 PDF 탭이 없습니다.',
    gatherNeedsAccess: '모을 PDF 탭이 없습니다. 웹 PDF를 찾으려면 위의 "웹 PDF도 ResearchPDF로 열기"를 켜세요.',
    gatherDone: (n: number) => `PDF ${n}개를 모았습니다.`,
    gatherWorking: 'PDF를 이 PDF 탭으로 모으는 중…',
    gatherKept: (n: number) => `원래 탭 ${n}개는 열어 두었습니다(아직 PDF 탭에 열리지 않았거나 탭이 너무 많음). PDF 탭에 들어간 것을 확인한 뒤 직접 닫으세요.`,
    gatherNoAnswer: 'PDF 탭이 답하지 않았습니다. 모은 PDF가 탭 줄에 있는지 확인하세요. 원래 탭은 닫지 않았을 수 있습니다.',
  },
  en: {
    // ── Page and navigation ──
    pageTitle: 'Settings · ResearchPDF',
    settings: 'Settings',
    searchSettings: 'Search settings',
    sectionsNav: 'Settings sections',
    chipSync: 'Sync',
    chipOpen: 'Opening PDFs',
    chipDisplay: 'Display',
    chipProjects: 'Projects',
    chipCapture: 'Figure capture',
    chipPaper: 'Paper info',
    chipStorage: 'Storage',
    chipKeys: 'Keyboard shortcuts',
    chipAbout: 'About',
    noMatch: 'No matching settings.',
    optional: 'Optional',
    thisDeviceOnly: 'This device only',

    // ── Sync ──
    syncTitle: 'Google Drive sync',
    syncDesc: 'Saves your annotations, reading positions, opened PDF list, and projects in a hidden app-only folder in your Google Drive, so they follow you across Chrome profiles and devices. It can’t see any other Drive files, and the PDF files themselves are not uploaded.',
    noAccount: 'No Google account connected.',
    syncNow: 'Sync now',
    syncUse: 'Use sync',
    syncUseSub: 'When off, this device stops exchanging data with Drive. The account stays connected.',
    connectGoogle: 'Connect Google account',
    connectOther: 'Connect a different account',
    disconnect: 'Disconnect',
    loginTrouble: 'If sign-in doesn’t work',
    googleAccount: 'Google account',
    signInHelp: 'If the Google sign-in window doesn’t open or ends in an error, check Chrome’s pop-up blocking and that you’re signed in, then try connecting again in a moment. If it still fails, report it under “Feedback and bug reports” with the “Details for developers” below.',
    signInUnavailable: 'Google Drive sync isn’t available in this copy of ResearchPDF (it was built without Google sign-in). Install ResearchPDF from the Chrome Web Store to use it.',
    devDetails: 'Details for developers',
    setupConfigured: (uri: string) => `If the sign-in window shows redirect_uri_mismatch, this install’s redirect URI isn’t registered with the OAuth client: ${uri}`,
    setupMissing: (uri: string) => `This build has no Google OAuth client ID. Set one up by following docs/google-drive-sync.md. Redirect URI to register: ${uri}`,
    syncing: 'Syncing…',
    syncError: (error: string) => `Sync error: ${error}`,
    lastSync: (when: string, pending: boolean) => `Last synced ${when}${pending ? ' · changes waiting to upload' : ''}`,
    waitingFirst: 'Waiting for the first sync.',
    syncOff: 'Sync is off.',
    syncHint: 'Once connected, syncs about every 15 minutes, and when you open or annotate a document.',
    syncStatusFailed: 'Couldn’t load the sync status.',
    signInOpening: 'Opening Google sign-in…',
    connectFailed: 'Couldn’t connect the Google account.',
    confirmAccountChange: (previous: string, next: string) => `This device’s papers, drawings, reading positions and projects have been syncing with the Google Drive of ${previous}.\n\nConnecting ${next} adds this device’s data to the Drive of ${next}. What is in the Drive of ${previous} stays there.\n\nConnect ${next}?`,
    accountChangeDeclined: 'Not connected.',
    disconnected: 'Disconnected. Data already saved in Drive stays there.',
    disconnectFailed: 'Couldn’t disconnect.',
    confirmDisconnect: (account: string) => `Disconnect ${account}?\n\nThis device stops syncing with Drive. The data saved in Drive, and the annotations and reading positions on this device, stay where they are.`,
    syncSwitchFailed: 'Couldn’t change the sync setting.',
    syncFailed: 'Sync failed.',

    // ── Opening PDFs ──
    openTitle: 'Opening PDFs',
    webPdfTitle: 'Open web PDFs in ResearchPDF',
    webPdfSub: 'Opens PDFs from web addresses (https://…) in the built-in viewer. Turning this on asks for site access, which is used only to fetch the PDF and show it in the viewer.',
    localPdfTitle: 'Open PDFs on your computer in ResearchPDF',
    localPdfSub: 'Opens PDFs from file:// in the built-in viewer instead of Chrome’s own. “Allow access to file URLs” must be on in the extension’s details in Chrome.',
    fileAccessOpen: 'Turn on in Chrome',
    hubScopeTitle: 'Where PDFs gather',
    hubScopeSub: 'A PDF tab per window: a PDF joins the PDF tab of the window it was opened in and never pulls another window forward — handy with several windows. One for the whole browser: each project has a single PDF tab, and PDFs go there from any window — for browsers where you switch spaces in one window (Arc and the like). With one window the two are the same.',
    hubScopeWindow: 'A PDF tab per window',
    hubScopeBrowser: 'One for the whole browser',
    restoreTitle: 'Restore closed PDF tabs',
    restoreSub: 'Chrome closes PDF tabs when the extension updates. They usually reopen on their own; use this if they didn’t.',
    restore: 'Restore',
    siteAccessOn: 'Site access allowed',
    siteAccessNeeded: 'Site access needed',
    fileUrlOn: 'File URL access on',
    fileUrlOff: 'File URL access off',
    siteDenied: 'Site access wasn’t allowed, so this couldn’t be turned on.',
    savedNotApplied: 'Saved, but couldn’t apply it. Reload the extension.',
    webOn: 'Web PDFs open in ResearchPDF. Reload PDF tabs that are already open.',
    webOff: 'Web PDFs open in Chrome’s own viewer.',
    localOff: 'PDFs on your computer open in Chrome’s own viewer.',
    localOn: 'PDFs on your computer open in ResearchPDF.',
    localNeedsAccess: 'Turned on. “Allow access to file URLs” must also be on in Chrome for this to work.',
    restoreFailed: 'Couldn’t restore PDF tabs.',
    restoredTabs: (n: number) => `Reopened ${n} PDF ${n === 1 ? 'tab' : 'tabs'}.`,
    nothingToRestore: (open: number) => `No tabs to restore (${open} PDF ${open === 1 ? 'tab is' : 'tabs are'} open).`,
    noTabHistory: 'No PDF tab history to restore.',

    // ── Display ──
    displayTitle: 'Display',
    languageTitle: '언어 / Language',
    languageSub: 'Open PDF tabs reload in the new language.',
    languageAuto: 'Automatic (browser language)',
    languageKo: '한국어',
    languageEn: 'English',
    tabTitle: 'Tab title',
    tabTitleSub: 'The name shown on the first line of a PDF tab.',
    tabTitlePaper: 'Paper title (PDF name if none)',
    tabTitleDocument: 'PDF title or file name',
    tabSubtitle: 'Tab subtitle',
    tabSubtitleSub: 'The second line of a tab. Not shown on pinned tabs.',
    tabSubtitleVenue: 'Venue and year',
    tabSubtitleOther: 'The other name (PDF name or paper title)',
    tabSubtitleNone: 'None — one line',
    kindIcons: 'Document type icons',
    kindIconsSub: 'Tells journal, conference, preprint, survey, and report papers apart by icon in tabs and Home.',
    kindIconsColor: 'Color icons',
    kindIconsMono: 'Icons only (one color)',
    kindIconsOff: 'Off — all document icons',
    projectFavicon: 'Project icon on Chrome tabs',
    projectFaviconSub: 'Replaces the Chrome tab icon of a PDF tab with its project’s icon, so you can tell project tabs apart at a glance.',

    // ── Projects ──
    projectsTitle: 'Projects',
    afterMove: 'After moving to another project',
    afterMoveSub: 'The notice that follows can undo the move or take you the other way.',
    afterMoveStay: 'Stay in this project',
    afterMoveFollow: 'Go along to that project',

    // ── Figure capture ──
    captureTitle: 'Figure capture',
    captureCopy: 'On capture',
    captureCopySub: 'What goes on the clipboard as soon as you select an area or click a figure or table. The panel beside the capture copies the rest.',
    captureCopyNone: 'Copy nothing',
    captureCopyImage: 'The image (slides)',
    captureCopyImageSource: 'Image and source (documents)',
    captureCopySource: 'The source only',
    captureEmbed: 'Source below the image',
    captureEmbedSub: 'Draws the source line into the image you copy or save.',
    captureStyle: 'Source format',
    captureStyleSub: 'APA is the same text as the paper strip’s APA copy.',
    captureStyleShort: 'Short',
    captureStyleApa: 'Full APA',
    capturePrefix: 'Source prefix',
    capturePrefixNone: 'None',
    captureDpi: 'Resolution',
    captureBackground: 'Background',
    captureWhite: 'White',
    captureTransparent: 'Transparent',
    captureAnnotations: 'Include annotations',
    captureAnnotationsSub: 'Draws your highlights, pen strokes and text notes into the image.',
    captureAutoDetect: 'Detect figures and tables',
    captureAutoDetectSub: 'In capture mode, outlines the figures and tables of the pages shown. A small model runs on each page, on this device. Off: capture by dragging only.',
    captureContinuous: 'Continuous capture',
    captureContinuousSub: 'Capture mode stays on after a copy. S or Esc turns it off.',

    // ── Paper info ──
    paperTitle: 'Paper info',
    paperShow: 'Show paper info',
    paperShowSub: 'When a paper is recognized (DOI, arXiv, or title), shows its venue, citation count and trend, references, and links. Only identifiers are sent to OpenAlex, Crossref, arXiv, and Semantic Scholar.',
    openalexKey: 'OpenAlex API key',
    openalexKeySub1: 'Without a key, everyone on the same network (IP address) shares one daily limit. Get a free key by signing up at ',
    openalexKeySub2: '.',
    s2Key: 'Semantic Scholar API key',
    s2KeySub1: 'Without a key, requests use the shared anonymous limit, so citation counts may be missing when it’s busy. Request a key at ',
    s2KeySub2: '.',
    save: 'Save',
    remove: 'Remove',
    check: 'Check',
    offline: 'Couldn’t connect. Check your network.',
    keySaved: 'Key saved',
    keyNone: 'No key',
    keyPlaceholderSaved: 'Saved — paste a new key and save to replace it',
    keyPlaceholderEmpty: 'Paste key',
    keySavedNote: 'Saved. Use “Check” to see whether it works.',
    keyRemoved: 'Key removed.',
    keyEmpty: 'No key pasted. To delete the saved key, use “Remove”.',
    checking: 'Checking…',

    // ── Storage ──
    storageTitle: 'Storage',
    cacheKeep: 'Keep opened PDFs on this device',
    cacheKeepSub: 'Keeps web PDFs you’ve opened on this device, so reopening doesn’t wait on the network. Now and then it compares with the server and tells you if there’s a newer version. The least recently used are deleted first, and nothing is sent to Drive.',
    savedPdfs: 'Saved PDFs',
    clearSavedPdfs: 'Clear saved PDFs',
    savedPdfsSize: 'Saved PDFs storage used',
    statLibrary: 'Opened PDFs',
    statAnnotated: 'Documents with annotations',
    statProjects: 'Projects',
    savedPdfsUsage: (files: number, used: string, max: string) => `${files} saved ${files === 1 ? 'PDF' : 'PDFs'} · ${used} / ${max}`,
    noSavedPdfs: 'No saved PDFs.',
    usageFailed: 'Couldn’t read the storage used.',
    countPapers: (n: number) => `${n}`,
    countProjects: (n: number) => `${n}`,
    cacheOn: 'Opened web PDFs are kept on this device.',
    cacheOff: 'No longer keeping PDFs. Use “Clear saved PDFs” to delete the ones already saved.',
    cacheCleared: 'Cleared all saved PDFs. Your annotations and reading positions are untouched.',
    confirmClearCache: (files: number, size: string) => `Delete ${files} saved ${files === 1 ? 'PDF' : 'PDFs'} (${size}) from this device?\n\nThey download again the next time you open them, except PDFs whose link has expired or that need a sign-in, which may not come back. Your annotations and reading positions are untouched.`,

    // ── Shortcuts ──
    keysTitle: 'Keyboard shortcuts',

    // ── About ──
    aboutTitle: 'About',
    homepage: 'Homepage',
    welcomeAgain: 'Show the welcome guide again',
    privacy: 'Privacy policy',
    feedback: 'Feedback and bug reports',
    webStore: 'Chrome Web Store',
    gatherTitle: 'Gather open PDFs',
    gatherSub: 'Moves PDFs open in Chrome’s own viewer into this PDF tab and closes their tabs. Their zoom comes along; the scroll position can’t (Chrome doesn’t share it with other extensions), so they resume where you left off only if ResearchPDF remembers it.',
    gatherButton: 'Gather',
    gatherNone: 'No PDF tabs to gather.',
    gatherNeedsAccess: 'No PDF tabs to gather. To find web PDFs, turn on “Open web PDFs in ResearchPDF” above.',
    gatherDone: (n: number) => `Gathered ${n} PDF${n === 1 ? '' : 's'}.`,
    gatherWorking: 'Gathering PDFs into this PDF tab…',
    gatherKept: (n: number) => `${n === 1 ? 'One original tab was' : `${n} original tabs were`} left open (not open in the PDF tab yet, or too many tabs). Close ${n === 1 ? 'it' : 'them'} yourself once you see ${n === 1 ? 'it' : 'them'} there.`,
    gatherNoAnswer: 'The PDF tab didn’t answer. Check its tab strip for the gathered PDFs; the original tabs may still be open.',
  },
});
