// Welcome page strings (welcome.html, welcome.ts).
import { messages } from '../shared/i18n';

export const S = messages({
  ko: {
    pageTitle: 'ResearchPDF 시작하기',
    language: '언어',
    next: '다음',
    back: '이전',
    skip: '건너뛰기',
    stepOf: (n: number, total: number) => `${n} / ${total}`,

    helloTitle: '안녕하세요! 👋',
    helloLead: 'ResearchPDF는 논문을 읽는 사람을 위한 PDF 뷰어입니다. 1분이면 준비가 끝납니다.',
    helloPoint1Title: '논문은 탭 하나에',
    helloPoint1: '웹과 컴퓨터의 PDF가 프로젝트별 탭 하나에 모입니다.',
    helloPoint2Title: '논문을 알아봅니다',
    helloPoint2: '게재처·인용 수·참고문헌을 바로 보여 주고, BibTeX도 한 번에.',
    helloPoint3Title: '필기가 따라옵니다',
    helloPoint3: '형광펜과 메모, 읽던 페이지가 내 Google Drive로 모든 기기에.',
    start: '시작하기',

    openTitle: 'PDF를 여기서 열까요?',
    openLead: '켜 두면 클릭한 PDF가 Chrome 기본 뷰어 대신 ResearchPDF로 열립니다. 언제든 설정에서 바꿀 수 있습니다.',
    webTitle: '웹 PDF',
    webSub: 'https:// 주소의 PDF. 켜면 Chrome이 사이트 접근 권한을 묻습니다 — PDF를 가져와 뷰어로 보내는 데만 씁니다.',
    webOn: '켜짐',
    webTurnOn: '켜기',
    webDenied: '권한이 허용되지 않았습니다. 나중에 설정에서 다시 켤 수 있습니다.',
    fileTitle: '컴퓨터의 PDF',
    fileSubOn: 'file:// 로 연 PDF도 ResearchPDF로 열립니다.',
    fileSubOff: 'Chrome의 확장 프로그램 세부정보에서 "파일 URL에 대한 액세스 허용"을 켜야 열립니다.',
    fileOn: '켜짐',
    fileOpenChrome: 'Chrome에서 켜기',

    gatherTitle: '지금 열린 PDF를 모을까요?',
    gatherLead: '다른 탭에 열려 있는 PDF를 PDF 탭 하나로 모읍니다.',
    gatherNone: '지금 열려 있는 PDF 탭이 없습니다.',
    gatherNeedsAccess: '웹 PDF를 찾으려면 앞 단계에서 웹 PDF를 켜야 합니다.',
    gatherCloseOriginals: '모은 뒤 원래 탭 닫기',
    gatherButton: (n: number) => `PDF ${n}개 모으기`,
    gatherDone: (n: number) => `PDF ${n}개를 PDF 탭으로 모았습니다.`,

    syncTitle: '모든 기기에서 이어 볼까요?',
    syncLead: 'Google 계정을 연결하면 필기, 읽던 페이지, 프로젝트가 내 Google Drive의 앱 전용 숨김 폴더를 통해 모든 Chrome 프로필과 기기를 따라옵니다. 이 폴더 밖의 Drive 파일은 볼 수 없고, PDF 파일은 올리지 않습니다.',
    syncConnect: 'Google 계정 연결',
    syncConnecting: 'Google 로그인 창을 여는 중…',
    syncConnected: (email: string) => `연결됨: ${email}`,
    syncFailed: '연결하지 못했습니다. 나중에 설정에서 다시 시도할 수 있습니다.',
    confirmAccountChange: (previous: string, next: string) => `이 기기의 논문, 필기, 읽던 위치와 프로젝트는 지금까지 ${previous} 계정의 Google Drive와 동기화했습니다.\n\n${next} 계정으로 연결하면 이 기기의 데이터가 ${next} 계정의 Drive에 더해집니다. ${previous} 계정의 Drive에 있는 데이터는 그대로 남습니다.\n\n${next} 계정으로 연결할까요?`,
    accountChangeDeclined: '연결하지 않았습니다. 나중에 설정에서 연결할 수 있습니다.',
    syncLater: '나중에 하기',

    tourTitle: '이렇게 씁니다',
    tourLead: 'ResearchPDF를 소개하는 짧은 논문을 열어, 아래 기능을 직접 해 보세요.',
    tourDemo: '데모 논문 열기',
    tourTabsTitle: '프로젝트별 PDF 탭',
    tourTabs: '탭 줄 왼쪽에서 프로젝트를 바꾸고, ⌂ 홈에서 열어 본 모든 논문을 찾습니다.',
    tourPaperTitle: '논문 정보 줄',
    tourPaper: '게재처·연도, 인용 추이, 참고문헌, BibTeX·APA 복사.',
    tourNotesTitle: '필기',
    tourNotes: '펜 버튼으로 형광펜·펜·메모. 다운로드하면 PDF에 함께 저장됩니다.',
    tourFiguresTitle: '그림·표 캡처',
    tourFigures: 'S: 영역 캡처 → 한 번 더: 그림·표 자동 인식. 누르면 출처와 함께 복사.',
    tourKeysTitle: '자주 쓰는 단축키',
    keyNext: '다음·이전 탭',
    keyClose: '탭 닫기',
    keyReopen: '닫은 탭 다시 열기',
    keyCapture: '그림 캡처',

    doneTitle: '준비 끝!',
    doneLead: '웹에서 PDF를 열거나, 파일을 PDF 탭에 끌어다 놓으면 시작됩니다. 설정은 PDF 탭 오른쪽 위 ⚙에 있습니다.',
    doneOpenTab: 'PDF 탭 열기',
    doneSettings: '설정 열기',
  },
  en: {
    pageTitle: 'Get started with ResearchPDF',
    language: 'Language',
    next: 'Next',
    back: 'Back',
    skip: 'Skip',
    stepOf: (n: number, total: number) => `${n} of ${total}`,

    helloTitle: 'Hello! 👋',
    helloLead: 'ResearchPDF is a PDF viewer for people who read papers. Setting it up takes a minute.',
    helloPoint1Title: 'Papers in one tab',
    helloPoint1: 'PDFs from the web and your computer gather in one tab per project.',
    helloPoint2Title: 'It knows the paper',
    helloPoint2: 'Venue, citations and references at a glance, BibTeX in one click.',
    helloPoint3Title: 'Notes follow you',
    helloPoint3: 'Highlights, notes and your page sync to every device via your Google Drive.',
    start: 'Get started',

    openTitle: 'Open PDFs here?',
    openLead: 'When on, PDFs you click open in ResearchPDF instead of Chrome’s own viewer. You can change this any time in settings.',
    webTitle: 'Web PDFs',
    webSub: 'PDFs at https:// addresses. Chrome asks for site access — used only to fetch the PDF and show it in the viewer.',
    webOn: 'On',
    webTurnOn: 'Turn on',
    webDenied: 'Access wasn’t granted. You can turn this on later in settings.',
    fileTitle: 'PDFs on your computer',
    fileSubOn: 'PDFs opened from file:// open in ResearchPDF too.',
    fileSubOff: 'Turn on “Allow access to file URLs” in the extension’s details in Chrome.',
    fileOn: 'On',
    fileOpenChrome: 'Turn on in Chrome',

    gatherTitle: 'Gather the PDFs open now?',
    gatherLead: 'Brings PDFs open in other tabs into one PDF tab.',
    gatherNone: 'No PDF tabs are open right now.',
    gatherNeedsAccess: 'Turn on web PDFs in the previous step to find web PDFs.',
    gatherCloseOriginals: 'Close the original tabs afterwards',
    gatherButton: (n: number) => `Gather ${n} PDF${n === 1 ? '' : 's'}`,
    gatherDone: (n: number) => `Gathered ${n} PDF${n === 1 ? '' : 's'} into the PDF tab.`,

    syncTitle: 'Pick up on every device?',
    syncLead: 'Connect a Google account and your annotations, reading positions and projects follow you to every Chrome profile and device through a hidden app-only folder in your Google Drive. It can’t see any other Drive files, and PDF files are never uploaded.',
    syncConnect: 'Connect Google account',
    syncConnecting: 'Opening Google sign-in…',
    syncConnected: (email: string) => `Connected: ${email}`,
    syncFailed: 'Couldn’t connect. You can try again later in settings.',
    confirmAccountChange: (previous: string, next: string) => `This device’s papers, drawings, reading positions and projects have been syncing with the Google Drive of ${previous}.\n\nConnecting ${next} adds this device’s data to the Drive of ${next}. What is in the Drive of ${previous} stays there.\n\nConnect ${next}?`,
    accountChangeDeclined: 'Not connected. You can connect later in settings.',
    syncLater: 'Maybe later',

    tourTitle: 'How it works',
    tourLead: 'Open a short paper about ResearchPDF and try each of these on it.',
    tourDemo: 'Open the demo paper',
    tourTabsTitle: 'A PDF tab per project',
    tourTabs: 'Switch projects at the left of the tab strip; ⌂ Home finds every paper you’ve opened.',
    tourPaperTitle: 'Paper info bar',
    tourPaper: 'Venue and year, citation trend, references, BibTeX and APA.',
    tourNotesTitle: 'Annotations',
    tourNotes: 'Highlighter, pen and notes from the pen button — saved into the PDF when you download it.',
    tourFiguresTitle: 'Figure capture',
    tourFigures: 'S: capture a region → again: find figures and tables. Click to copy with the source.',
    tourKeysTitle: 'Handy shortcuts',
    keyNext: 'Next / previous tab',
    keyClose: 'Close tab',
    keyReopen: 'Reopen closed tab',
    keyCapture: 'Figure capture',

    doneTitle: 'All set!',
    doneLead: 'Open a PDF on the web, or drop a file onto the PDF tab, to begin. Settings are under ⚙ at the top right of the PDF tab.',
    doneOpenTab: 'Open PDF tab',
    doneSettings: 'Open settings',
  },
});
