// Paper database check strings (apiStatus.ts).
import { messages } from './i18n';

export const S = messages({
  ko: {
    underMinute: '1분 미만',
    hours: (h: number) => `${h}시간`,
    hoursMinutes: (h: number, m: number) => `${h}시간 ${m}분`,
    minutes: (m: number) => `${m}분`,
    resetsIn: (duration: string) => ` · ${duration} 뒤 초기화`,
    budget: (remaining: string, limit: string) => `오늘 남은 요청 ${remaining} / ${limit}`,
    oaBadKey: 'OpenAlex가 이 키를 받지 않습니다. 키를 다시 확인하세요.',
    oaKeyLimit: (reset: string) => `이 키의 한도를 다 썼습니다${reset}.`,
    oaNoKeyLimit: (reset: string) => `이 네트워크의 키 없는 일일 한도를 다 썼습니다${reset}. 무료 키를 넣으면 따로 한도를 받습니다.`,
    oaWorksKey: '키가 동작합니다',
    oaWorksNoKey: '키 없이 동작합니다 (네트워크 공용 한도)',
    oaNoAnswer: (status: number) => `OpenAlex가 응답하지 않습니다 (HTTP ${status}).`,
    s2NoAnswerKey: '응답을 받지 못했습니다. 네트워크를 확인하거나 잠시 뒤 다시 확인하세요.',
    s2NoAnswerNoKey: '응답을 받지 못했습니다. 키 없는 공용 한도가 붐빌 때 흔히 이렇습니다. 잠시 뒤 다시 확인하거나 키를 넣으세요.',
    s2BadKey: 'Semantic Scholar가 이 키를 받지 않습니다. 키를 다시 확인하세요.',
    s2LimitKey: '요청 제한에 걸렸습니다. 잠시 뒤 다시 시도하세요.',
    s2LimitNoKey: '키 없는 공용 한도가 지금 붐빕니다(429). 키를 넣으면 안정적으로 조회됩니다.',
    s2WorksKey: '키가 동작합니다.',
    s2WorksNoKey: '키 없이 동작합니다 (공용 한도, 붐비면 실패할 수 있음).',
    s2NoAnswer: (status: number) => `Semantic Scholar가 응답하지 않습니다 (HTTP ${status}).`,
  },
  en: {
    underMinute: 'under 1 min',
    hours: (h: number) => `${h} h`,
    hoursMinutes: (h: number, m: number) => `${h} h ${m} min`,
    minutes: (m: number) => `${m} min`,
    resetsIn: (duration: string) => ` · resets in ${duration}`,
    budget: (remaining: string, limit: string) => `${remaining} of ${limit} requests left today`,
    oaBadKey: 'OpenAlex doesn’t accept this key. Check the key and try again.',
    oaKeyLimit: (reset: string) => `This key’s limit is used up${reset}.`,
    oaNoKeyLimit: (reset: string) => `This network’s daily limit without a key is used up${reset}. A free key gets its own limit.`,
    oaWorksKey: 'Key works',
    oaWorksNoKey: 'Works without a key (limit shared across the network)',
    oaNoAnswer: (status: number) => `OpenAlex isn’t responding (HTTP ${status}).`,
    s2NoAnswerKey: 'No response. Check your network, or try again in a moment.',
    s2NoAnswerNoKey: 'No response. This is common when the shared limit without a key is busy. Try again in a moment, or add a key.',
    s2BadKey: 'Semantic Scholar doesn’t accept this key. Check the key and try again.',
    s2LimitKey: 'Rate limit reached. Try again in a moment.',
    s2LimitNoKey: 'The shared limit without a key is busy right now (429). Add a key for reliable lookups.',
    s2WorksKey: 'Key works.',
    s2WorksNoKey: 'Works without a key (shared limit; may fail when busy).',
    s2NoAnswer: (status: number) => `Semantic Scholar isn’t responding (HTTP ${status}).`,
  },
});
