// Strings of the shared modules (pdfAnnotations, pdfLibrary, hubTabs, syncErrors).
import { messages } from './i18n';

const EN_MONTHS = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];

export const S = messages({
  ko: {
    // Annotation labels (conflict dialog)
    labelText: '텍스트',
    labelHighlight: '형광펜',
    labelImage: '이미지',
    labelPen: '펜',
    labelNote: '메모',
    labelUnderline: '밑줄',
    labelStrikeOut: '취소선',
    labelSquiggly: '물결 밑줄',
    labelSquare: '사각형',
    labelCircle: '원',
    labelLine: '선',
    labelPolygon: '다각형',
    labelPolyLine: '꺾은선',
    labelCaret: '삽입 표시',
    labelFileAttachment: '첨부 파일',
    labelSound: '소리',
    labelRedact: '가림',
    labelAnnotation: '주석',
    pageNumber: (n: number) => `${n}쪽`,
    // Relative time
    justNow: '방금',
    minutesAgo: (n: number) => `${n}분 전`,
    hoursAgo: (n: number) => `${n}시간 전`,
    daysAgo: (n: number) => `${n}일 전`,
    dateThisYear: (month: number, day: number) => `${month}월 ${day}일`,
    dateOtherYear: (year: number, month: number, day: number) => `${year}. ${month}. ${day}.`,
    // arXiv version badge
    latestVersion: '최신',
    // Display name of the default project (the stored name stays '기본')
    defaultProjectName: '기본',
    // Sync errors (shared/syncErrors.ts)
    syncErrAuthBadResponse: 'Google 로그인 응답이 올바르지 않습니다.',
    syncErrAuthVerifyFailed: 'Google 로그인 응답을 검증하지 못했습니다.',
    syncErrAuthExpired: 'Google 로그인이 만료되었습니다. 설정에서 Google 계정을 다시 연결하세요.',
    syncErrAuthDenied: 'Google 계정 접근이 허용되지 않았습니다.',
    syncErrAuthFailed: 'Google 로그인에 실패했습니다.',
    syncErrAuthDriveDenied: 'Google Drive 앱 데이터 접근 권한이 허용되지 않았습니다.',
    syncErrAuthServerUnreachable: 'Google 인증 서버에 연결하지 못했습니다.',
    syncErrTokenVerifyFailed: 'Google 토큰을 검증하지 못했습니다.',
    syncErrNotConfigured: '이 빌드에는 Google 동기화가 구성되어 있지 않습니다.',
    syncErrAuthCancelled: 'Google 로그인이 취소되었습니다.',
    syncErrAccountMismatch: '연결된 Google 계정과 다른 계정으로 로그인되어 있습니다. 설정에서 다시 연결하세요.',
    syncErrDriveFileTooLarge: 'Google Drive의 동기화 파일이 너무 큽니다.',
    syncErrDriveReadFailed: 'Google Drive의 동기화 파일을 읽지 못했습니다.',
    syncErrDriveQuota: 'Google Drive 저장 공간이 부족합니다.',
    syncErrDriveRateLimited: 'Google Drive 요청 한도를 초과했습니다. 잠시 후 다시 시도하세요.',
    syncErrDriveDenied: 'Google Drive 접근이 거부되었습니다.',
    syncErrDriveHttp: (status: string) => `Google Drive 요청이 실패했습니다 (HTTP ${status}).`,
    syncErrDriveBadUrl: 'Google Drive 요청 주소가 올바르지 않습니다.',
    syncErrTimeout: '동기화 요청 시간이 초과되었습니다.',
    syncErrDriveUnreachable: 'Google Drive에 연결하지 못했습니다.',
    syncErrDriveBadResponse: 'Google Drive 응답을 해석하지 못했습니다.',
    syncErrDriveUploadSession: 'Google Drive 업로드 세션을 열지 못했습니다.',
    syncErrDriveUploadUnverified: 'Google Drive 업로드 결과를 확인하지 못했습니다.',
    syncErrAccountInfoFailed: 'Google 계정 정보를 확인하지 못했습니다.',
    syncErrDriveFileChanging: 'Google Drive 파일이 계속 변경되어 읽지 못했습니다. 잠시 후 다시 시도하세요.',
    syncErrAccountChanged: '동기화 중 Google 계정 연결이 바뀌어 이전 결과를 적용하지 않았습니다.',
    syncErrFileInvalid: 'Google Drive의 동기화 파일이 유효한 ResearchPDF 문서가 아닙니다.',
    syncErrFileTooNew: 'Google Drive의 동기화 파일을 이 버전에서 읽을 수 없습니다.',
    syncErrConnectFirst: '설정에서 Google 계정을 먼저 연결하세요.',
    syncErrSyncOff: '클라우드 동기화가 꺼져 있습니다.',
    syncErrFailed: '클라우드 동기화에 실패했습니다.',
    syncErrConflict: '다른 기기와 동시에 동기화되어 충돌했습니다. 다시 시도하세요.',
  },
  en: {
    labelText: 'Text',
    labelHighlight: 'Highlight',
    labelImage: 'Image',
    labelPen: 'Pen',
    labelNote: 'Note',
    labelUnderline: 'Underline',
    labelStrikeOut: 'Strikethrough',
    labelSquiggly: 'Squiggly underline',
    labelSquare: 'Rectangle',
    labelCircle: 'Circle',
    labelLine: 'Line',
    labelPolygon: 'Polygon',
    labelPolyLine: 'Polyline',
    labelCaret: 'Insert mark',
    labelFileAttachment: 'File attachment',
    labelSound: 'Sound',
    labelRedact: 'Redaction',
    labelAnnotation: 'Annotation',
    pageNumber: (n: number) => `p. ${n}`,
    justNow: 'just now',
    minutesAgo: (n: number) => `${n} min ago`,
    hoursAgo: (n: number) => `${n} h ago`,
    daysAgo: (n: number) => `${n} ${n === 1 ? 'day' : 'days'} ago`,
    dateThisYear: (month: number, day: number) => `${EN_MONTHS[month - 1]} ${day}`,
    dateOtherYear: (year: number, month: number, day: number) => `${EN_MONTHS[month - 1]} ${day}, ${year}`,
    latestVersion: 'latest',
    defaultProjectName: 'Default',
    syncErrAuthBadResponse: 'Unexpected response from Google sign-in.',
    syncErrAuthVerifyFailed: 'Couldn’t verify the Google sign-in response.',
    syncErrAuthExpired: 'Google sign-in expired. Reconnect your Google account in settings.',
    syncErrAuthDenied: 'Access to the Google account wasn’t allowed.',
    syncErrAuthFailed: 'Google sign-in failed.',
    syncErrAuthDriveDenied: 'Access to Google Drive app data wasn’t granted.',
    syncErrAuthServerUnreachable: 'Couldn’t reach Google’s authentication server.',
    syncErrTokenVerifyFailed: 'Couldn’t verify the Google token.',
    syncErrNotConfigured: 'Google sync isn’t set up in this build.',
    syncErrAuthCancelled: 'Google sign-in was cancelled.',
    syncErrAccountMismatch: 'You’re signed in with a different account than the connected Google account. Reconnect in settings.',
    syncErrDriveFileTooLarge: 'The sync file on Google Drive is too large.',
    syncErrDriveReadFailed: 'Couldn’t read the sync file on Google Drive.',
    syncErrDriveQuota: 'Google Drive is out of storage.',
    syncErrDriveRateLimited: 'Google Drive request limit exceeded. Try again in a moment.',
    syncErrDriveDenied: 'Google Drive access was denied.',
    syncErrDriveHttp: (status: string) => `Google Drive request failed (HTTP ${status}).`,
    syncErrDriveBadUrl: 'Invalid Google Drive request URL.',
    syncErrTimeout: 'The sync request timed out.',
    syncErrDriveUnreachable: 'Couldn’t connect to Google Drive.',
    syncErrDriveBadResponse: 'Couldn’t parse the Google Drive response.',
    syncErrDriveUploadSession: 'Couldn’t open a Google Drive upload session.',
    syncErrDriveUploadUnverified: 'Couldn’t confirm the Google Drive upload result.',
    syncErrAccountInfoFailed: 'Couldn’t verify the Google account info.',
    syncErrDriveFileChanging: 'The Google Drive file kept changing, so it couldn’t be read. Try again in a moment.',
    syncErrAccountChanged: 'The Google account connection changed during sync, so the earlier result wasn’t applied.',
    syncErrFileInvalid: 'The sync file on Google Drive isn’t a valid ResearchPDF document.',
    syncErrFileTooNew: 'This version can’t read the sync file on Google Drive.',
    syncErrConnectFirst: 'Connect a Google account in settings first.',
    syncErrSyncOff: 'Cloud sync is turned off.',
    syncErrFailed: 'Cloud sync failed.',
    syncErrConflict: 'Another device synced at the same time and caused a conflict. Try again.',
  },
});
