// Keyboard shortcut descriptions (shortcuts.ts: the settings page, the welcome tour, README).
import { messages } from './i18n';

export const S = messages({
  ko: {
    groupTabs: 'PDF 탭',
    groupView: '보기',
    groupAnnotate: '필기·캡처',
    prevNextTab: '이전·다음 PDF 탭',
    closeTab: '지금 PDF 탭 닫기',
    reopenTab: '닫은 탭 다시 열기',
    moveInProject: '프로젝트 목록에서 순서 옮기기',
    find: '문서에서 찾기',
    findNext: '다음·이전 찾은 곳',
    zoom: '확대·축소',
    fit: '자동 맞춤',
    rotate: '왼쪽·오른쪽으로 회전',
    firstLast: '첫·마지막 페이지',
    print: '인쇄',
    download: '다운로드 (필기 포함)',
    undoRedo: '실행 취소·다시 실행',
    capture: '영역 캡처 → 한 번 더: 그림·표 자동 인식 → 한 번 더: 끄기',
    escape: '캡처·찾기·필기 도구 닫기',
  },
  en: {
    groupTabs: 'PDF tabs',
    groupView: 'View',
    groupAnnotate: 'Annotate and capture',
    prevNextTab: 'Previous / next PDF tab',
    closeTab: 'Close this PDF tab',
    reopenTab: 'Reopen closed tab',
    moveInProject: 'Reorder in the project list',
    find: 'Find in document',
    findNext: 'Next / previous match',
    zoom: 'Zoom in / out',
    fit: 'Fit automatically',
    rotate: 'Rotate left / right',
    firstLast: 'First / last page',
    print: 'Print',
    download: 'Download (with annotations)',
    undoRedo: 'Undo / redo',
    capture: 'Capture an area → again: auto-detect figures and tables → again: turn off',
    escape: 'Close capture, find, and annotation tools',
  },
});
